### ISSUE TITLE
Vary:Origin should be set on response even if Origin:xxx is not on request

### ISSUE THREAD

**Issue by drbild** [fruitcake/laravel-cors#20]
If the response does not contain a Origin header, then the Vary:Origin header and CORS headers are not sent on the response.  This causes any subsequent HTTP caches (e.g., Varnish) to cache and serve the response _without_ CORS headers for future requests that _do_ specify a valid Origin header.

**Comment by wimleers** [comment]
asm89/stack-cors#11 was merged 1.5 year ago.

**Comment by wimleers** [comment]
>  In this case I tend to agree with your story and we should probably always add the `Vary` header. 

> If stack-cors is changed to set the Vary header even on requests without an Origin, then this laravel-cors will need to be changed to always load the middleware

> Yes I know, if this has been changed, and asm89/stack-cors#11 or similar has merged + tagged, ping me back and I'll change that.

… but actually asm89/stack-cors#11 _did not_ change this. It is still not adding the `Vary: Origin` header _always_.
