### ISSUE TITLE
[Proposal] Implement same origin verification with headers (simple CSRF protection)

### ISSUE THREAD

**Issue by Frondor** [fruitcake/laravel-cors#257]
## Why
I liked this package's implementation, and I'm about to use it on production, but found some redundancy at the time of handling CRSF protection for a RESTful API. 
If I want to make some _safety_ checks (verify same origin) to prevent CSRF, I'll be probably using `CorsService` class to check for `Origin` and `Referer` headers, and compare them against the `AllowedHeaders` array, More about this idea: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Verifying_Same_Origin_with_Standard_Headers

Before explaining my approach, I'd like to quote something from that link:

> There are some situations where the Origin header is not present.
> - Internet Explorer 11 does not add the Origin header on a CORS request across sites of a trusted zone. The Referer header will remain the only indication of the UI origin.
> - Following a 302 redirect cross-origin. In this situation, the Origin is not included in the redirected request because that may be considered sensitive information you don't want to send to the other origin. But since we recommend rejecting requests that don't have both Origin and Referer headers, this is OK, because the reason the Origin header isn't there is because it is a cross-origin redirect.

And also:
> Checking the Referer Header
If the Origin header is not present, verify the hostname in the Referer header matches the target origin. Checking the Referer is a commonly used method of preventing CSRF on embedded network devices because it does not require any per-user state. This makes Referer a useful method of CSRF prevention when memory is scarce or server-side state doesn't exist. This method of CSRF mitigation is also commonly used with unauthenticated requests, such as requests made prior to establishing a session state which is required to keep track of a synchronization token.

> In both cases, just make sure the target origin check is strong. For example, if your site is "site.com" make sure "site.com.attacker.com" doesn't pass your origin check (i.e., match through the trailing / after the origin to make sure you are matching against the entire origin).

Actually, [`CorsService` assumes that `Origin` header is always present](https://github.com/barryvdh/laravel-cors/blob/1326460c591e5299d43e266de52a4141c5c66561/src/CorsService.php#L175), now I'll suggest to create a new `$origin` property and a `setOrigin` method on that class, the method runs within `__construct()` and checks wether `Origin` or `Referer` (fallback) headers are present.
Stop making use of `$request->headers->get('origin')`, use `$this->origin` instead.

And then the protection would be something like:

```php
private $options;
private $origin;

public function __construct(array $options = array())
{
    $this->options = $this->normalizeOptions($options);
    $this->origin= $this->setOrigin(request()); // DI would be better
}
protected function setOrigin(Request $request)
{
    $origin = $request->headers->get('Origin');
    $refererHost = $request->headers->get('Referer'); // TO-DO return only referer's host, not full path

    if ($this->options['detectCSRF']) {
        if (!$origin && !$refererHost || $origin && $refererHost && $origin !== $refererHost)
            throw CSRFException;
	}

    /**
     * If we don't want to rely on $refererHost when $origin is null, then above logic could go
     * here: https://github.com/barryvdh/laravel-cors/blob/1326460c591e5299d43e266de52a4141c5c66561/src/CorsService.php#L176
     */
	
    return $origin ? $origin : $refererHost;
}
```
I know CSRF protection is not on this package's scope, but it could help a lot (thos avoiding multiple checks on same things like headers' presence) if provides optional functionality for this. We can use a config array to implement this.

Basically what it does is setting the `$origin` property of `CorsService` class via `setOrigin` and at the same time, check for a possible CSRF attack before proceeding with the `allowedHeaders` array checks.

Brief explaining (following [OWASP](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Verifying_Same_Origin_with_Standard_Headers) guidelines):
1. Determining the origin the request is coming from (source origin) ( `$this->origin === null`)
		- if (!originHeader && !refererHeader) throw CSRFException
2. Verifying the Two Origins Match
		- elseif (origin && referer && origin !== referer) throw CSRFException
3. Determining the origin the request is going to (target origin)
		- if (originAndOrHeader matches (allowedOrigins[])) return next()

What do you think?

**Comment by barryvdh** [comment]
I'm closing this because it's currently out of scope.
