### ISSUE TITLE
web services

### ISSUE THREAD

**Issue by pratuljak** [fruitcake/laravel-cors#295]
Failed to load http://worldtimepiece.com/Android/getdata.php: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
core.js:1448 ERROR Responseheaders: Headers_headers: Map(0) {}size: (...)__proto__: Mapclear: ƒ clear()constructor: ƒ Map()delete: ƒ delete()entries: ƒ entries()forEach: ƒ forEach()get: ƒ ()has: ƒ has()keys: ƒ keys()set: ƒ ()size: (...)values: ƒ values()Symbol(Symbol.iterator): ƒ entries()Symbol(Symbol.toStringTag): "Map"get size: ƒ size()__proto__: Object[[Entries]]: Array(0)length: 0_normalizedNames: Map(0)size: (...)__proto__: Mapclear: ƒ clear()constructor: ƒ Map()delete: ƒ delete()entries: ƒ entries()forEach: ƒ forEach()get: ƒ ()has: ƒ has()keys: ƒ keys()set: ƒ ()size: (...)values: ƒ values()Symbol(Symbol.iterator): ƒ entries()Symbol(Symbol.toStringTag): "Map"get size: ƒ size()__proto__: Object[[Entries]]: Array(0)length: 0__proto__: Objectok: falsestatus: 0statusText: ""type: 3url: null_body: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://worldtimepiece.com/Android/getdata.php", __zone_symbol__loadfalse: null, __zone_symbol__errorfalse: null, __zone_symbol__xhrListener: ƒ, …}defaultPrevented: falseeventPhase: 0isTrusted: truelengthComputable: falseloaded: 0path: []returnValue: truesrcElement: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://worldtimepiece.com/Android/getdata.php", __zone_symbol__loadfalse: null, __zone_symbol__errorfalse: null, __zone_symbol__xhrListener: ƒ, …}target: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://worldtimepiece.com/Android/getdata.php", __zone_symbol__loadfalse: null, __zone_symbol__errorfalse: null, __zone_symbol__xhrListener: ƒ, …}timeStamp: 13184.999999999945total: 0type: "error"__proto__: ProgressEvent__proto__: Body
defaultErrorLogger @ core.js:1448

**Comment by pratuljak** [comment]
please help me about this error

**Comment by GrahamCampbell** [comment]
You'd be best asking on some kind of support forum for this sort of thing. This is the issue tracker for the library core itself.

**Comment by barryvdh** [comment]
It also doesn't seem like a Laravel webservice?
