### ISSUE TITLE
preflight error in two different server

### ISSUE THREAD

**Issue by SajjadKharrazi** [fruitcake/laravel-cors#329]
hi
my Laravel Api service was in a server that worked correctly, with cPanel and below config:

Apache Version | 2.4.34
PHP Version | 7.1

now i moved all Laravel files and databases in a new server with directAdmin and like previous server config.
but now i get preflight error.
i use ionic and laravel 5.5.

whats happened? what can i do?

`Kernel.php`
```php
protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Barryvdh\Cors\HandleCors::class,
    ];

**Comment by Jeffrey-Lang** [comment]
I have the same issue, just asked the provider if they disabled CROS on a higher level.

**Comment by barryvdh** [comment]
Closing this as there have been significant changes. Please check with the latest 1.x branch and make sure to checkout the changes described in the Readme.
