### ISSUE TITLE
Support for Laravel method spoofing

### ISSUE THREAD

**Issue by teeli** [fruitcake/laravel-cors#347]
I'm using laravel-cors on Laravel 5.2 and on a resource controller the `Allow` header contains `GET,HEAD,PUT,PATCH` when calling an update route. This doesn't work with [Laravel's method spoofing](https://laravel.com/docs/5.2/routing#form-method-spoofing), which allows setting the method as `POST` and define the method parameter `_method` as `PUT`. When `_method` is present in the request, laravel-cors then should probably allow `POST` for update routes in resource controllers, right?

One use case for this feature is file uploads to existing objects using API requests and FormData. File uploads only work using `POST` method, but laravel-cors is blocking from using `POST` in update calls.

**Comment by barryvdh** [comment]
Method spoofing should be enabled with the latest versions.
