### ISSUE TITLE
preg_match(): No ending delimiter '*' found

### ISSUE THREAD

**Issue by fendiseptiawan0709** [fruitcake/laravel-cors#351]
I have installed your package via composer. When I'm try to test it out, something went wrong.
It return **500 - Internal Server Error**. When I check it, it says
 
```
exception: "ErrorException"
file: "/var/www/html/dokternet-server/vendor/asm89/stack-cors/src/Asm89/Stack/CorsService.php"
line: 185
message: "preg_match(): No ending delimiter '*' found"
```

I've been follow your instruction on your docs.
I'm using [Global Middleware](https://github.com/barryvdh/laravel-cors#global-usage) as your documentation.

Here is my **[HAR file](https://drive.google.com/open?id=11U1RyKbMyL7H7gY33XMnFfN1nWmjdDMW)**, I hope it helps you to solve this problem.
Please help me to solve this problem, thanks.

composer.json : 
**"laravel/framework": "5.5.*"**
**"barryvdh/laravel-cors": "^0.11.2"**

**Comment by PaulLawton227** [comment]
We're also getting a log of these errors in our logs too.

        "laravel/framework": "5.8.*",
        "barryvdh/laravel-cors": "^0.11.3",

cors.php
```    
   'supportsCredentials' => true,
    //    'allowedOrigins' => ['*'],
    'allowedOrigins' => [   ----- array of urls removed ------  ],
    'allowedOriginsPatterns' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,

```

**Comment by barryvdh** [comment]
The * can be used with Origins, not OriginPatters. I've cleared this up in the docs.
