### ISSUE TITLE
Rename suggestion: Off-CORS

### ISSUE THREAD

**Issue by rienheuver** [fruitcake/laravel-cors#353]
Just thought this name would be nice to have. Turning CORS off for API applications sometimes just feels so logical... of course! Ehh... Off-CORS!

**Comment by Langstra** [comment]
Off cors I want this.

**Comment by barryvdh** [comment]
Well, CORS = Cross-Origin Resource Sharing, so you actually want to enable sharing resources on cross-origin requests, so you want CORS ON for certain routes.
