### ISSUE TITLE
Get request with Authorization header not working :(

### ISSUE THREAD

**Issue by Chykay** [fruitcake/laravel-cors#358]
I am trying to consume the laravel API with angular. i sent a Get request together with an Authorization header to a laravel passport API i created and i keep getting 

> OPTIONS http://remote.com/api net::ERR_EMPTY_RESPONSE

Apparently the request is preflighted and the server is not sending a response back for the OPTIONS header. Help! I implemented your plugin

**Comment by msl2000** [comment]
Somewhat similar issue. After the OPTIONS request, the post request cant find my bearer token. It returns a null.

**Comment by matthabermehl** [comment]
Make sure you set the origin header on your Ajax request. I just noticed that the middleware determines if something's a CORS request by checking if it has an origin header, and being a CORS request is a condition for dealing with the OPTIONS preflight.

**Comment by xulei2016** [comment]
hei bro,did you fixed it ???

**Comment by barryvdh** [comment]
For Authorization headers, make sure you set supports_credentials to true in the config.
