### ISSUE TITLE
CORS headers are not always added to error responses

### ISSUE THREAD

**Issue by ce-brex** [fruitcake/laravel-cors#359]
Error responses don't include the CORS headers unless the middleware is activated globally.  Assigning the middleware to a route group will return headers properly only on successful (2xx) responses. This makes sense in that the middleware isn't applied until the route is matched by laravel.  Other than including this in the service provider like the preflight check middleware is included, I'm not sure of a proper work around.

**Comment by alexszilagyi** [comment]
@ce-brex : Have you found any workaround ? Currently facing the same issue.

**Comment by winter-ice** [comment]
If you fount this issue when you response error 404,check the `$middlewarePriority` in `Kernel.php`.
Make sure the middleware which response header before `SubstituteBindings`.
In my case,i response `Authorization` header with jwt.refresh and add 'Authorization' in` cors.php` config file `exposedHeaders`.
but there has issue.
After debug, i found solution is add `RefreshToken` middleware before `SubstituteBindings` in `$middlewarePriority`.
Hopefully that helps 😄

**Comment by ce-brex** [comment]
@alexszilagyi The only workaround I was able to do at the moment was add it as a global middleware.

@winter-ice This won't work, the route doesn't exist so will never get matched and have any middleware applied to it.

**Comment by alexszilagyi** [comment]
@ce-brex : Can you share how you've achieved that?

I'm interested to take in consideration all your changes regarding to CORS.

**Comment by ce-brex** [comment]
@alexszilagyi  Just follow the Global Usage instructions in the documentation.  Add the call to the `HandleCors` middleware in the `$middleware` property of `app/Http/Kernel.php`.  This makes it a global middleware and will apply to all requests.

**Comment by alexszilagyi** [comment]
@ce-brex : I'm using Lumen `5.3.x` and as for `app/Http/Kernel.php ` there's no such file. Isn't `app/Console/Kernel.php ` ?

**Comment by ce-brex** [comment]
@alexszilagyi For Lumen, you would it to the `$app->middleware()` call in `bootstrap/app.php`.  It should be about half way in the file where it talks about registering middleware.

**Comment by alexszilagyi** [comment]
@ce-brex : Thanks, it seems I've found the core problem.

The issue which I've faced is regarding to queues, if I'm using `QUEUE_DRIVER=database` works perfectly but when using `QUEUE_DRIVER=sync`.

Not sure if anyone tried similar things and what was the final workaround.

**Comment by rambii** [comment]
My workaround for this is disabling the global `bindings`-middleware in the Kernel.php.
Afterwards I need to call the bindings on every route like so 
`Route::group(['middleware' => 'bindings'], function () ...` 
and calling the cors middleware before the bindings middlware where applicable like so 
`Route::group(['middleware' => [\Barryvdh\Cors\HandleCors::class, 'bindings']], function() ...`

**Comment by ce-brex** [comment]
Has nothing to do with the order of the middlewares (linked issue was fixed in 5.3).  Errors, more specifically 404 responses, are not caught by any routes, so route specified middlewares will not be applied.  Global middlewares are the only ones that will be processed.  If you want CORS headers on error responses, you need to add the `HandleCors` middleware to the global middlewares.

**Comment by rambii** [comment]
@ce-brex yes, I didn't mean the issue itself but the general approach.
I didn't add the CORS middleware globally but for route groups only and then it sends CORS headers even if the route model is not found and returns a 404

**Comment by ce-brex** [comment]
@rambii Ah yes, I think I follow now.  I'm curious if you're using implicit or explicit model binding.  We're using explicit with custom resolution logic that throws `ModelNotFoundException` at different points.  I wonder if throwing those manually is affecting how the cors headers are being handled.

**Comment by rambii** [comment]
@ce-brex as far as I understand it's implicit. I use the built in route model binding in Laravel which was defined in the Kernel.php. I disabled the middleware there and included it in the route group.
Did you register your custom resolution logic globally? If so, did you try to add it via a route group after the CORS middleware?
E.g.
```
```

**Comment by CitizenBeta** [comment]
Did anyone find a solution? I think I may have posted a duplicate issue here:

https://github.com/barryvdh/laravel-cors/issues/364

**Comment by rambii** [comment]
@CitizenBeta yes, looks like a similar problem. 
Did you try the approach I described above? I still use this approach in production and it's working for me.

**Comment by CitizenBeta** [comment]
@rambii I'm uncertain over what exactly I would be changing. Right now I have CORS on my API middleware per the documentation. Should I remove it?

**Comment by rambii** [comment]
@CitizenBeta I described what I did here https://github.com/barryvdh/laravel-cors/issues/359#issuecomment-512195822

**Comment by andreshg112** [comment]
Same to @madebycaliper.
![imagen](https://user-images.githubusercontent.com/15859884/80502320-17dfbe80-8936-11ea-9ce6-3fe70b6d2f93.png)

**Comment by barryvdh** [comment]
Yeah might add a note about this.
