### ISSUE TITLE
Access-Control-Allow-Origin on PUT, PATCH and DELETE methods

### ISSUE THREAD

**Issue by WeeHong** [fruitcake/laravel-cors#360]
I am facing the CORS issue when calling the method of `PUT`, `PATCH` or `DELETE`.

![57433618_408003526691982_734015412739506176_n](https://user-images.githubusercontent.com/6753022/55931153-107c4300-5c57-11e9-8b7b-b28a6d826867.jpg)

I am using Axios to consume the API services running by Laravel.
I installed the package and setup the `config/cors.php` with the following codes.
```
'supportsCredentials' => false,
'allowedOrigins' => ['*'],
'allowedOriginsPatterns' => [],
'allowedHeaders' => ['*'],
'allowedMethods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
'exposedHeaders' => [],
'maxAge' => 0,
```

I also added the CORS on the `app/Http/Kernel.php` like the following,
```
protected $middleware = [
    ...
    \Barryvdh\Cors\HandleCors::class,
];
```

I understand similar kind of issues has been raised by a few of the users but I cannot find any solution which can help me rectify my issue.

**Comment by WeeHong** [comment]
I managed to find a solution after a few days.

If you have already applied the method of `GET, POST, PUT, PATCH and DELETE` on the `allowedMethods` but still facing this CORS error.

Please go back and check the controller which pointed by the route.
Ensure your code don't have `echo` keyword.
This will lead to an error of CORS.

Example
```
public function update(Request $request, $id)
{
    return "Success"; // This one works fine
    echo "Success"; // This one will return CORS error
}
```
Thanks for this post. 

https://github.com/barryvdh/laravel-cors/issues/341#issuecomment-434209940

**Comment by alexszilagyi** [comment]
@WeeHong: Tried your approach but without success.  Can you specify what version of PHP, Lumen & barryvdh/laravel-cors you're using?

**Comment by grupoargentinoinfo** [comment]
> I managed to find a solution after a few days.
> 
> If you have already applied the method of `GET, POST, PUT, PATCH and DELETE` on the `allowedMethods` but still facing this CORS error.
> 
> Please go back and check the controller which pointed by the route.
> Ensure your code don't have `echo` keyword.
> This will lead to an error of CORS.
> 
> Example
> 
> ```
> public function update(Request $request, $id)
> {
>     return "Success"; // This one works fine
>     echo "Success"; // This one will return CORS error
> }
> ```
> 
> Thanks for this post.
> 
> [#341 (comment)](https://github.com/barryvdh/laravel-cors/issues/341#issuecomment-434209940)

That solved my problem! Thank you!

**Comment by ElnurIbrahimzade** [comment]
@WeeHong could you specify your laravel verison and provide your APP\HTTP\Kernel file ?

**Comment by ElnurIbrahimzade** [comment]
@WeeHong add this to your kernel.php
```
/**
     * The priority-sorted list of middleware.
     *
     * This forces non-global middleware to always be in the given order.
     *
     * @var array
     */
    protected $middlewarePriority = [
          \Barryvdh\Cors\HandleCors::class,
          ...
    ];
```

**Comment by chuoke** [comment]
just now. This issue appears after I update the version from v1.0.0 to v1.0.3.

**Comment by barryvdh** [comment]
Closing this as there have been significant changes. Please check with the latest 1.x branch and make sure to checkout the changes described in the Readme. If this is still an issue, please create a new issue.
