### ISSUE TITLE
Readme slight confusion re: common problems and errors

### ISSUE THREAD

**Issue by matthabermehl** [fruitcake/laravel-cors#361]
I wonder if it would be worth leaving out the parenthetical "Pre Laravel 5.3" in the "Common problems and errors" title of the Readme. The requirement of an origin header, for example, still seems to be relevant in Laravel 5.8.

**Comment by barryvdh** [comment]
I added some common problems here: https://github.com/fruitcake/laravel-cors/commit/1bd392eb3cac940be035d346bf715e96a6d507f1
