### ISSUE TITLE
Chrome CORB warning for preflight request.

### ISSUE THREAD

**Issue by christiaan-lombard** [fruitcake/laravel-cors#362]
Chrome is logging CORB warnings for OPTIONS requests:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type text/html. See <URL> for more details.
```

See [https://www.chromestatus.com/feature/5629709824032768](https://www.chromestatus.com/feature/5629709824032768)

This does not break anything since the OPTIONS preflight-request is still accepted, but could this be avoided by responding with a 204 status instead of 200?

barryvdh/laravel-cors: v0.11.3
laravel/framework: v5.8.15
Chrome: v74.0.3729.157

**Comment by blindsz** [comment]
any fixed on this?

**Comment by reneroth** [comment]
this should be fixed upstream in https://github.com/asm89/stack-cors

**Comment by barryvdh** [comment]
So is this now fixed?

**Comment by barryvdh** [comment]
See https://github.com/asm89/stack-cors/pull/52
