### ISSUE TITLE
PostMan still gets to API

### ISSUE THREAD

**Issue by movepixels** [fruitcake/laravel-cors#371]
Maybe I am going about this all wrong or simply not understanding.

I have a Laravel API and a Vue front end application. I want the API to only be accessable when requests are coming from the Vue front end.

Frontend url = www.somesite.com
API backend url = http://api.somesite.com

But even on localhost / and live server I can make a request via postman and it always gets thru.
I went to an online API tester and sent the login request to live server and it still get thru.

Here is cors.php config:
```
'supportsCredentials' => false,
'allowedOrigins' => [
  's******p.com', // this should be only url that can access the API?
],
//'allowedOrigins' => ['*'],
'allowedHeaders' => ['Origin', 'Content-Type', 'Accept', 'Authorization', 'Cache-Control', 'X-Requested-With'],
'allowedMethods' => ['GET', 'PUT', 'PATCH', 'POST', 'DELETE'],
'exposedHeaders' => ['Authorization'],
'maxAge' => 0
```

Added the ```\Barryvdh\Cors\HandleCors::class,``` to kernel.php in all guards since none are working figured all to all. ($middleware, $middlewareGroups / api and web, $routeMiddleware)

The api.php routes is wrapped in 
```
Route::group(['middleware' => ['cors']], function () {
/// all api routes
});
```

Any ideas where I am going wrong?
Thanks all,

Dave

**Comment by AminMkh** [comment]
browser check for CORs as a security measurement, Postman doesn't care.
Check this:
https://stackoverflow.com/questions/36250615/cors-with-postman

**Comment by mammadataei** [comment]
@AminMkh 
> browser check for CORs as a security measurement, Postman doesn't care.
> Check this:
> https://stackoverflow.com/questions/36250615/cors-with-postman

So why the back-end doesn't prevent the request?

**Comment by AminMkh** [comment]
CORS basically tell the browser whether it's safe to do certain actions on the server remotely. If backend said no access to my API from remote server, browser will stop the request.

**Comment by barryvdh** [comment]
Yes cors is not a firewall, you can still make requests without Origin headers (eg with php), so it's not a firewall or anything.
