### ISSUE TITLE
[QUESTION] Do we have to define a different route for the OPTIONS that only returns 200?

### ISSUE THREAD

**Issue by bicatu** [fruitcake/laravel-cors#382]
Lumen 5.8

I have a route like this

```
$router->post(
                    'doX',
                    [
                        'uses'       => 'DoXController@index'
                    ]
                );
```
I wonder if to enable CORS of the above API I would simply add
```
      'middleware' => ['cors'],
```

To the definition or do I have to have a $router->options(....) instead?
Also, do I point to the same uses or simply return anything as content?

**Comment by barryvdh** [comment]
You shouldn't have to define OPTIONS manually.
