### ISSUE TITLE
Argument 1 passed to Asm89\Stack\CorsService::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by fingersandmind** [fruitcake/laravel-cors#384]
I sure do followed everything on the documentaion. But idk why I'm getting this kind of error.

Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Asm89\Stack\CorsService::__construct() must be of the type array, null given, called in /home/fingersandmind/Documents/Laravel Project/allcool/vendor/barryvdh/laravel-cors/src/ServiceProvider.php on line 37 in file /home/fingersandmind/Documents/Laravel Project/allcool/vendor/asm89/stack-cors/src/Asm89/Stack/CorsService.php on line 22

#0 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/barryvdh/laravel-cors/src/ServiceProvider.php(37): Asm89\Stack\CorsService->__construct(NULL)
#1 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Barryvdh\Cors\ServiceProvider->Barryvdh\Cors\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build(Object(Closure))
#3 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('Asm89\\Stack\\Cor...', Array)
#4 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('Asm89\\Stack\\Cor...', Array)
#5 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(946): Illuminate\Foundation\Application->make('Asm89\\Stack\\Cor...')
#6 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(874): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(835): Illuminate\Container\Container->resolveDependencies(Array)
#8 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build('Barryvdh\\Cors\\H...')
#9 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('Barryvdh\\Cors\\H...', Array)
#10 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('Barryvdh\\Cors\\H...', Array)
#11 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(160): Illuminate\Foundation\Application->make('Barryvdh\\Cors\\H...')
#12 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/fingersandmind/Documents/Laravel Project/allcool/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#15 /home/fingersandmind/Documents/Laravel Project/allcool/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#16 /home/fingersandmind/Documents/Laravel Project/allcool/server.php(21): require_once('/home/fingersan...')
#17 {main}

**Comment by patrickcarlohickman** [comment]
That error would only happen if your cors config is null. Considering the package has a default config, that shouldn't happen.

Taking a look at the code, the only way that I can see this happening is if you're on Laravel 6 and your config is cached. Laravel 6 updated the `Illuminate\Support\ServiceProvider::mergeConfigFrom()` method to not merge configs when the config is cached.

If this is the case, refresh your config cache and that should fix the error.

Additionally, if this is the case, the package documentation should probably add a note for this for Laravel 6 users.

**Comment by fingersandmind** [comment]
@patrickcarlohickman Yes. Solve it by running php artisan optimize. Leaving it here for reference

**Comment by patrickcarlohickman** [comment]
@fingersandmind Yeah, `artisan optimize` calls `config:cache`, so that should work, too.

**Comment by hugeps** [comment]
Not working for me, config:cache done 
config file is there.


In HandleCors.php line 20:

  Argument 1 passed to Fruitcake\Cors\HandleCors::__construct() must be an instance of Asm89\Stack\CorsService, insta
  nce of Illuminate\Foundation\Application given, called in /home/huge/dview/portal/vendor/laravel/framework/src/Illu
  minate/Foundation/ProviderRepository.php on line 208

**Comment by patrickcarlohickman** [comment]
@hugeps That is a different error than the for this issue. I would suggest submitting a new issue.

On that note, however, based on your error message, it seems like your application is trying to register `Fruitcake\Cors\HandleCors` as a service provider. Did you add this class to your providers array in your `config/app.php` config file? If so, that is not correct.

**Comment by hugeps** [comment]
Added to config/app.php.
This was suggested in the Readme.
If not correct what is the right way to make use of this provider?

**Comment by barryvdh** [comment]
The ServiceProvider is added by Laravel automatically. You only need to add it to the global middleware in your Http Kernel

**Comment by hugeps** [comment]
Perfect and thank you, trying this now.

**Comment by DeveloperAlbertoF** [comment]
Not working
