### ISSUE TITLE
[RFC] [1.0] Drop Laravel 5.8

### ISSUE THREAD

**Issue by GrahamCampbell** [fruitcake/laravel-cors#389]
Laravel 6 is LTS, so it probably makes sense to drop 5.8 from 1.0 when it is released, and go with 6 LTS upwards, like 0.11 was 5.5 LTS upwards.

FYI, Laravel 5.5 and 5.8 are no longer supported for bug fixes. In fact, actually, Laravel 5.8 support ended 4 days before 5.5's ended. So kinda odd to retain support for 5.8 but not 5.5. ;)

---

https://laravel.com/docs/6.x/releases#support-policy

**Comment by barryvdh** [comment]
Yeah I've added 5.5 support. There doesnt seem to be any difference from 5.5 so I'll keep it in here for now, and drop as soon as changes are required that are incompatible.
