### ISSUE TITLE
Unable to locate publishable resources when following readme

### ISSUE THREAD

**Issue by guiltyvictim** [fruitcake/laravel-cors#396]
I've followed the instructions step by step:

```composer require fruitcake/laravel-cors```

Add `\Fruitcake\Cors\HandleCors::class,` to `app/Http/Kernel.php`

Next, I don't have the `config/cors.php` file, so I use the following command, as mentioned in the Configuration section:

```php artisan vendor:publish --provider="Fruitcake\Cors\CorsServiceProvider"```

And I get this error:

```Unable to locate publishable resources.```

Unfortunately I'm not really familiar with Laravel and these artisan commands or namespaces, but I assume this has something to do with the namespaces have changed recently? I got to this package via barryvdh/laravel-cors but it's now called fruitcake, and maybe some other things have changed and is not reflected?

**Comment by jwxy-knight** [comment]
composer require barryvdh/laravel-cors
Add \Barryvdh\Cors\HandleCors::class, to app/Http/Kernel.php
php artisan vendor:publish --provider="Barryvdh\Cors\CorsServiceProvider"
it's ok

**Comment by barryvdh** [comment]
Which version are you using?

**Comment by rishijasapara** [comment]
I am facing the same issue. It shows 'Publishing Complete' in the command line, but cors.php file is not created under the 'config' folder.

**Comment by barryvdh** [comment]
Sorry, something went wrong with the v1 tag. Can you update to v1.0.2?
https://github.com/fruitcake/laravel-cors/releases/tag/v1.0.2

php artisan vendor:publish --tag=cors

**Comment by rishijasapara** [comment]
v1.0.2 solves the problem. Thanks much! I couldn't try the artisan command since I manually copied cors.php into the config folder, and it's working fine at the moment.

**Comment by rulatir** [comment]
Still experiencing this as of 1.0.5.

**Comment by spacedog4** [comment]
Still experiencing this as of 2.0.

**Comment by keigokeigo** [comment]
Hi, @rulatir .

I had a same problem but solved by removing `/vendor` directory and restarting `composer require fruitcake/laravel-cors` from scratch.

Hope it will work out.


> Still experiencing this as of 1.0.5.
