### ISSUE TITLE
\Fruitcake\Cors\ServiceProvider does not exist in package

### ISSUE THREAD

**Issue by Mathem8tic** [fruitcake/laravel-cors#400]
According to vendor/fruitcake/laravel-cors/src/CorsServiceProvider.php the readme is referencing a file which has been renamed to CorsServiceProvider.php.

**Comment by barryvdh** [comment]
Thanks, updated in https://github.com/fruitcake/laravel-cors/commit/719be21aa7ba9ac0e48b273e71bb2886b80e868e
