### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by marbuser** [fruitcake/laravel-cors#401]
Using the latest version of Laravel and PHP 7.4, installed this package and upon trying to load a view it gives me the error;
`Trying to access array offset on value of type null`

Specifically from this file;
`vendor/fruitcake/laravel-cors/src/CorsServiceProvider.php:26`

I thought it might be because of PHP 7.4, so I downgraded to 7.3 but still having the same issue.

Let me know if more information is required.

**Comment by barryvdh** [comment]
Did you publish your config?

**Comment by itskibo** [comment]
I had the same issue, and publishing the config didn't make the issue disappear.

I ran the following commands after publishing the config, and that seemed to fix the problem for me:
- `composer dump`
- `artisan optimize`

I'm assuming that running `artisan optimize` is enough, so you might wanna try that @marbuser.

**Comment by barryvdh** [comment]
Yes make sure the config is valid and not cached.
