### ISSUE TITLE
Package just doesn't work at all and doesn't set headers.

### ISSUE THREAD

**Issue by marbuser** [fruitcake/laravel-cors#402]
I was previously using `barryvdh/laravel-cors` and that worked perfectly fine. Since this seems to be the "newer" version of that I decided to just update to this, and upon updating everything is broken and there is no clear indication as to why.

I'm using Laravel as a REST API and I'm using a VueJS frontend to interact with it. Upon sending a request from my VueJS dev server to my Valet Laravel domain, I just instantly get 401'd on an OPTIONS request with it claiming `Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

And sure enough, there is no header on the response which I thought was sort of the point of this package?

I've followed the instructions to a tee, and I'm not even using anything crazy advanced. Currently I've just set my options to allow all origins like so;
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS Options
    |--------------------------------------------------------------------------
    |
    | The allowed_methods and allowed_headers options are case-insensitive.
    |
    | You don't need to provide both allowed_origins and allowed_origins_patterns.
    | If one of the strings passed matches, it is considered a valid origin.
    |
    | If array('*') is provided to allowed_methods, allowed_origins or allowed_headers
    | all methods / origins / headers are allowed.
    |
    */

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['*'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => [],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header.
     */
    'exposed_headers' => false,

    /*
     * Sets the Access-Control-Max-Age response header.
     */
    'max_age' => false,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,
];
```

I've got no idea what the issue is and it's incredibly frustrating that the previous version worked and this new one doesn't...

And for anyone wondering, no I'm not using `dd()` or `dump()` or anything similar that would be causing this issue.

**Comment by barryvdh** [comment]
Did you add the middleware globally?

**Comment by Melcus** [comment]
@marbuser in `cors.php` file, set `'paths' => ['*']`

**Comment by barryvdh** [comment]
@Melcus He has that in his config.

**Comment by Melcus** [comment]
@barryvdh saw that and deleted the message right when you posted, my bad

**Comment by prgt4u** [comment]
@barryvdh got same problem.
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS Options
    |--------------------------------------------------------------------------
    |
    | The allowed_methods and allowed_headers options are case-insensitive.
    |
    | You don't need to provide both allowed_origins and allowed_origins_patterns.
    | If one of the strings passed matches, it is considered a valid origin.
    |
    | If array('*') is provided to allowed_methods, allowed_origins or allowed_headers
    | all methods / origins / headers are allowed.
    |
    */

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['api/*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['*'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => [],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header.
     */
    'exposed_headers' => false,

    /*
     * Sets the Access-Control-Max-Age response header.
     */
    'max_age' => false,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => true,
];
`

**Comment by barryvdh** [comment]
How does your Kernel.php look like.

**Comment by sebdesign** [comment]
We had a similar issue. After upgrading our `Kernel.php` looked like this:
```php
protected $middlewareGroups = [
    'api' => [
        // ...
        \Fruitcake\Cors\HandleCors::class,
    ],
];
```

But when we read the [release notes](https://github.com/fruitcake/laravel-cors/releases/tag/v1.0.0) we switched to this:
```php
protected $middleware = [
        // ...
        \Fruitcake\Cors\HandleCors::class,
];
```

We also replaced the `config/cors.php` and changed the `paths` value to `['api/*']` and now the middleware works correctly.

**Comment by pierrocknroll** [comment]
@barryvdh the upgrade process is a nightmare, please make an UPGRADE.MD and explain what is this new parameter "path", it seems that it needs a value, but is empty by default !

**Comment by barryvdh** [comment]
There is a changelog here: https://github.com/fruitcake/laravel-cors/blob/master/changelog.md#v10-2019-12-27
But I'll add it to the readme

**Comment by barryvdh** [comment]
See https://github.com/fruitcake/laravel-cors/commit/9b04376f420839aec2cc7f184d1c2ca9b558ba08
