### ISSUE TITLE
Wildcard  for allowed_origins

### ISSUE THREAD

**Issue by hamid80386** [fruitcake/laravel-cors#403]
It seem we need a way for use wildcards for allowed_origins

for example

`
'allowed_origins' => ['(https|http)://*.domainname.com'],
`
Can i find any similar way in this module?

**Comment by barryvdh** [comment]
You can use `allowed_origins_patterns`

**Comment by emargareten** [comment]
@barryvdh does `allowed_origins_patterns` allow wildcard subdomains?

**Comment by barryvdh** [comment]
Yes just use *.yourdomain.com

**Comment by barryvdh** [comment]
This has been updated in the readme. Wildcards in the allowedOrigins will be automatically converted to actual patterns.
