### ISSUE TITLE
Wrong Namespace

### ISSUE THREAD

**Issue by NickDelBen** [fruitcake/laravel-cors#408]
Currently, the version of `fruitcake/laravel-cors` that composer pulls has the wrong namespace, and thus the readme is inaccurate.

When you pull the package with composer you can see the namespace remained `\Barryvdh\Cors`.

The readme says to add the laravel middleware as so:
```
protected $middleware = [
    // ...
    \Fruitcake\Cors\HandleCors::class,
];
```
however this gives a class not found exception because inside the php code we can see the old namespace.

tl;dr Either update the composer package to use the fruitcake namespace, or change the readme to the following:
```
protected $middleware = [
    // ...
    \Barryvdh\Cors\HandleCors::class,
];
```

**Comment by barryvdh** [comment]
Which version do you have?

**Comment by NickDelBen** [comment]
This was our fault however i do believe this is unintended behaviour.

We ran `composer require fruitcake/laravel-cors` and version 1.0.0 was installed.

We had to manually specify 1.0.3 to get the latest.

**Comment by barryvdh** [comment]
Yeah that release is borked. Not sure why you got it though. I've removed it completely now.
