### ISSUE TITLE
Undefined type '\Fruitcake\Cors\HandleCors'

### ISSUE THREAD

**Issue by michael-ottink** [fruitcake/laravel-cors#410]
After installing the package in my Laravel project with `composer require fruitcake/laravel-cors` and running `composer update` and adding `\Fruitcake\Cors\HandleCors::class,` to my middleware in my Kernal.php I get the following error undefined type '\Fruitcake\Cors\HandleCors::class,' intelephense . I'm using Laravel 6.1. Why is this happening? I tried clearing the conifg a composer dump-autoload.

**Comment by barryvdh** [comment]
Sorry, I don't understand your question. What is intelephense? Intellisensense? Is it your IDE?

**Comment by MichaelOttink** [comment]
It's a plugin for code completion aid in Visual Studio Code. It does not see the Fruitcake namespace.

**Comment by barryvdh** [comment]
But do you get an actual error? Otherwise, Visual Code probably hasn't indexed it.

**Comment by ce-brex** [comment]
This isn't an issue with this package.  You need to have Intelephense reindex the workspace to see the changes in the namespace.
