### ISSUE TITLE
New laravel-cors do not work with Laravel Framework 5.8.36

### ISSUE THREAD

**Issue by fgenao-cuore** [fruitcake/laravel-cors#411]
I'm able to get data properly with GET request but, other requests like POST is not working.

**Laravel Framework 5.8.36**

**config/cors.php**

return [
    'paths' => ['public/api/*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => false,
    'max_age' => false,
    'supports_credentials' => false,
];
**Kernel.php**

    protected $middleware = [
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
    ];
![Selection_142](https://user-images.githubusercontent.com/55023776/72897605-53903a00-3cf0-11ea-871d-03f2dc850a46.png)

**Comment by barryvdh** [comment]
I think public shouldn't be in your path.

**Comment by od3n** [comment]
you can try add ` Fruitcake\Cors\CorsServiceProvider::class,` to your config/app.php under provider

**Comment by barryvdh** [comment]
Please try with the latest version and make sure you follow all instructions.

**Comment by marcellopato** [comment]
I was facing the same problem here on my 5.8.* Laravel app.
Reinstalled from stretch and now it is working fine!
