### ISSUE TITLE
Response to preflight request doesn't pass access control check: It does not have HTTP ok status

### ISSUE THREAD

**Issue by artmerlop** [fruitcake/laravel-cors#412]
I get the following error:

Access to XMLHttpRequest at 'https://sub.example.com/api/test' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

This is my Kernel.php

```
namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Fruitcake\Cors\HandleCors::class,
    ];

```
And this is my config/cors.php

```
<?php

return [
    'paths' => ['api/*'],
    'allowed_methods' => ['GET', 'POST'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => false,
    'max_age' => false,
    'supports_credentials' => false,
];

```

**Comment by barryvdh** [comment]
Did you clear your config cache?

**Comment by artmerlop** [comment]
@barryvdh yes, like a thousand times, I tried using postman, and the request is successful, also the project in local is successful, the issue is when I test it on the server. I have other projects using laravel-cors older versions and they work perfectly, the issue is only with this latest version.

**Comment by shadowgroundz** [comment]
Hi, I have some issue too

**Comment by shadowgroundz** [comment]
> Hi, I have some issue too

I solved my problem. Actually I have different issue. 

> Response to preflight request doesn't pass access control check: Redirect not allowed. 

At my frontend, I hit API with '/' at the end, but work perfectly if I not use it. And I didn't know why my API took long time in browser. But if I use swagger or postman result return faster

**Comment by GotaloveCode** [comment]
> @barryvdh yes, like a thousand times, I tried using postman, and the request is successful, also the project in local is successful, the issue is when I test it on the server. I have other projects using laravel-cors older versions and they work perfectly, the issue is only with this latest version.

Any luck with this.Am stuck on the same scenario.I set up on local it worked fine but on server am getting No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by GotaloveCode** [comment]
> > @barryvdh yes, like a thousand times, I tried using postman, and the request is successful, also the project in local is successful, the issue is when I test it on the server. I have other projects using laravel-cors older versions and they work perfectly, the issue is only with this latest version.
> 
> Any luck with this.Am stuck on the same scenario.I set up on local it worked fine but on server am getting No 'Access-Control-Allow-Origin' header is present on the requested resource.

In case someone else faces the same issue. Mine turned out to be incorrect permissions with storage.Totally unrelated to the cors package.

**Comment by artmerlop** [comment]
Apparently that's the issue, it's not about the package is about permissions, I fixed my issue changing them for storage and bootstrap/cache folders.

```
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```
Toked me a day to realize that was the issue, jaja, I hope this helps.

**Comment by dhruvkumarsood** [comment]
CORS issue can be simply resolved by following this:

Create a new shortcut of Google Chrome( any browser, update browser installation path accordingly) with following value:

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="D:\chrome\temp"`

**Comment by richardabear** [comment]
@dhruvkumarsood that will not fix the issue for consumers of the API (people on regular chrome browsers)

**Comment by dhruvkumarsood** [comment]
I made an edit. That is for developers

**Comment by AditModi** [comment]
> > > @barryvdh yes, like a thousand times, I tried using postman, and the request is successful, also the project in local is successful, the issue is when I test it on the server. I have other projects using laravel-cors older versions and they work perfectly, the issue is only with this latest version.
> > 
> > 
> > Any luck with this.Am stuck on the same scenario.I set up on local it worked fine but on server am getting No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> In case someone else faces the same issue. Mine turned out to be incorrect permissions with storage.Totally unrelated to the cors package.

@GotaloveCode , I am facing the same issue. my application is a bit different ( node + nginx ) but would still like to know how to solve this issue.

**Comment by GotaloveCode** [comment]
@AditModi I have faced this before on nginx as well.Turned out to be conflicting php-fpm versions in my nginx config file. Check nginx error log if there is an error. If not check your permissions for storage.
