### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by AhmadAudeh** [fruitcake/laravel-cors#413]
I have solved my issue, but just wanted to share:
After updating to v1.0.3 I have got this error : 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource
Even after following the instruction for the update, I thought I done everything right. 
The catch was in config/cors.php : 
`'paths' => [],`
Since I am enabling CORS on all my routes, so I thought the correct syntax is an empty value, but it was not. After changing the configuration 
`'paths' => ['/*'],`
Everything is working fine now :)

**Comment by AhmadAudeh** [comment]
Solved 👍

**Comment by barryvdh** [comment]
How?

**Comment by barryvdh** [comment]
Oh sorry, you've edited it already. Cool :)
