### ISSUE TITLE
Only GET requests work with laravel 6

### ISSUE THREAD

**Issue by GabMic** [fruitcake/laravel-cors#415]
Laravel Version: 6.13
PHP Version: 7.4.2
Database Driver & Version: MySQL

### Description:
Only GET request accepted when CORS are enabled. No POST, PUT. OPTIONS.Using the laravel-cors package, and set up it as usual like in the docs.

### Steps To Reproduce:
Use laravel-cors or some kind of cors middleware on laravel version 6 and send a POST\PUT request.

**Comment by pslxx** [comment]
![image](https://user-images.githubusercontent.com/8417207/73646469-79d0b500-46b4-11ea-8b20-b44cda359bf4.png)
it  work

![image](https://user-images.githubusercontent.com/8417207/73646504-8bb25800-46b4-11ea-96bc-28dce3c68349.png)
doesn't work

**Comment by barryvdh** [comment]
See https://github.com/fruitcake/laravel-cors#upgrading-from-0x

Group middleware is no longer supported.
A new 'paths' property is used to enable/disable CORS on certain routes. This is empty by default!

**Comment by meirtin** [comment]
not working for me

**Comment by meirtin** [comment]
@GabMic maybe you have dd() in somewhere of your code, try making a simple response()->json([],200)

**Comment by pslxx** [comment]
> See https://github.com/fruitcake/laravel-cors#upgrading-from-0x
> 
> Group middleware is no longer supported.
> A new 'paths' property is used to enable/disable CORS on certain routes. This is empty by default!

tks...

**Comment by jm21** [comment]
````
return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS Options
    |--------------------------------------------------------------------------
    |
    | The allowed_methods and allowed_headers options are case-insensitive.
    |
    | You don't need to provide both allowed_origins and allowed_origins_patterns.
    | If one of the strings passed matches, it is considered a valid origin.
    |
    | If array('*') is provided to allowed_methods, allowed_origins or allowed_headers
    | all methods / origins / headers are allowed.
    |
    */

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['api/*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['*'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => ['*'],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header.
     */
    'exposed_headers' => false,

    /*
     * Sets the Access-Control-Max-Age response header.
     */
    'max_age' => false,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,
];
````
