### ISSUE TITLE
Adding cors package in service provider

### ISSUE THREAD

**Issue by midwestE** [fruitcake/laravel-cors#422]
Works great!  

May be worth adding a tidbit to the readme that includes how to add this package in a service provider as its taken me a bit to figure it out:

``
public function boot()
    {
        $this->app['Illuminate\Contracts\Http\Kernel']->prependMiddleware(\Fruitcake\Cors\HandleCors::class);
    }
``

**Comment by barryvdh** [comment]
Why do you need it in a service provider instead of the Kernel?

**Comment by midwestE** [comment]
Because I am using https://github.com/nWidart/laravel-modules and the functionality is specific to when that module is installed/enabled.

**Comment by designvoid** [comment]
@midwestE I am also using the Modules package having issues - any chance you could elaborate on your solution for myself and any future users?

**Comment by darron1217** [comment]
same situation, same problem here.

I don't want to apply cors on every request. I tried to apply it on specific routes and this lead OPTIONS request to fail.

**Comment by barryvdh** [comment]
Yeah that's why you should add it to the global middleware, and set the paths config option to restrict CORS.

**Comment by darron1217** [comment]
I want to make this code work...
```
        \Route::group([
            'prefix' => '/api',
            'middleware' => [HandleCors::class]
        ], function($router) {
            $router->post('login', [
                'as' => 'api.auth.login',
                'uses' => 'AuthController@postLogin'
            ]);
        });
```

**Comment by barryvdh** [comment]
okay goodluck then.

**Comment by darron1217** [comment]
you mean that there's no way to acheive it with this package, right?

**Comment by barryvdh** [comment]
You probably could get most of it working by adding a fallback route in the group, to catch the options.

**Comment by darron1217** [comment]
Got it. Thanks.
