### ISSUE TITLE
No 'Access-Control-Allow-Origin' with base64 data

### ISSUE THREAD

**Issue by Krystus** [fruitcake/laravel-cors#428]
Access to XMLHttpRequest at 'http://x.x/v1/media/store' from origin 'http://localhost:3002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Standard forms works without ant problems. Error is present only while I try to pass base64 media in request by Axios post, from Nuxt (Vue) to my API in Laravel.

```
<?php

return [

    'paths' => ['v1/*'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => false,

    'max_age' => false,

    'supports_credentials' => false,

];
```

**Comment by Krystus** [comment]
Something related?

```
dev.ERROR: implode(): Invalid arguments passed {"userId":8,"exception":"[object] (ErrorException(code: 0): implode(): Invalid arguments passed at /home/vagrant/x/vendor/asm89/stack-cors/src/Asm89/Stack/CorsService.php:94)
[stacktrace]
```

**Comment by Brandutchmen** [comment]
Same issue here :/

**Comment by barryvdh** [comment]
If you have that error, it would seem that `exposed_headers` is something other then `false` but not an array. Can you update to the latest version and double-check your config (and clear the cache?)

**Comment by Brandutchmen** [comment]
I am currently on 1.0.5.
I have tried clearing my cache.
My config is a direct copy of the template, except I have:
'paths' => ['*'],

Thoughts?

**Comment by Brandutchmen** [comment]
Error: 
`Access to XMLHttpRequest at 'http://localhost:6001/socket.io/?EIO=3&transport=polling&t=N3FD_67' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Config: (I'm experimenting with allowed_headers)
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS Options
    |--------------------------------------------------------------------------
    |
    | The allowed_methods and allowed_headers options are case-insensitive.
    |
    | You don't need to provide both allowed_origins and allowed_origins_patterns.
    | If one of the strings passed matches, it is considered a valid origin.
    |
    | If array('*') is provided to allowed_methods, allowed_origins or allowed_headers
    | all methods / origins / headers are allowed.
    |
    */

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['*'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => ['*'],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => [
        '*',
        'Content-Type',
        'X-Auth-Token',
        'Origin',
        'Authorization',
        'Access-Control-Allow-Origin',
    ],

    /*
     * Sets the Access-Control-Expose-Headers response header.
     */
    'exposed_headers' => false,

    /*
     * Sets the Access-Control-Max-Age response header.
     */
    'max_age' => false,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,
];
`

**Comment by Brandutchmen** [comment]
Here is the request details according to chrome:
`
GET /socket.io/?EIO=3&transport=polling&t=N3FEaAe HTTP/1.1
Host: localhost:6001
Connection: keep-alive
Accept: */*
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Origin: http://localhost:8000
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: http://localhost:8000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
`

**Comment by barryvdh** [comment]
socket.io? Is that running through your laravel application?

**Comment by Brandutchmen** [comment]
I am running socket.io to connect my Vue application to my laravel-webhooks instance on localhost:6001. I am new to socket.io, so my setup might be wrong as well.

**Comment by barryvdh** [comment]
socket.io has nothing to do with how you configure laravel-cors. You should handle CORS there.

**Comment by Brandutchmen** [comment]
Okay. I will look into that. Thank you!

**Comment by barryvdh** [comment]
@Krystus how are you processing the media? Are you returning the response or die()/echo() somewhere?

**Comment by Krystus** [comment]
@barryvdh after composer update problem is no longer present.

`Updating fruitcake/laravel-cors (v1.0.4 => v1.0.5): Downloading (100%)`
