### ISSUE TITLE
Laravel must be add provider to config/app.php

### ISSUE THREAD

**Issue by 631991669** [fruitcake/laravel-cors#429]
config/app.php
`
'providers' => [
    Fruitcake\Cors\CorsServiceProvider::class,
}
`
if  not ,the cors.php can't load for middleware.

**Comment by od3n** [comment]
yes this works for me too on Laravel 5.7.28

**Comment by barryvdh** [comment]
This should be done automatically with auto registering since 5.5

**Comment by bbotto-pdga** [comment]
Sorry to wake the dead, but I'm seeing this same issue on Laravel 5.6.  I have to manually add the provider in `config/app.php` like the OP.  Any idea why?
