### ISSUE TITLE
CORS not working when "api" endpoint is not "api" (Laravel 7)

### ISSUE THREAD

**Issue by alainbelez** [fruitcake/laravel-cors#430]
i created a new laravel 7 project and i have change the prefix of the api endpoints to admin.

i also changed the `paths` in cors.php to `admin/*` however, i cannot seem to make it work. reverting everything back to api does work, any idea why?

**Comment by barryvdh** [comment]
Is the routes is config cached?

**Comment by alainbelez** [comment]
oddly enough. i tried clearing it again, after i sent this message it, it worked. seems like config are being cached when called.
