### ISSUE TITLE
"Preflight response is not successful" on all iOS mobile browsers

### ISSUE THREAD

**Issue by i-ira** [fruitcake/laravel-cors#437]
Across every browser on iOS 13 (13.3 specifically), none of the POST request made from my subdomain to my base domain's api are working. Upon inspection via Safari, I see the following error:

<img width="1200" alt="Screen Shot 2020-03-21 at 2 39 27 AM" src="https://user-images.githubusercontent.com/41458922/77221240-76877080-6b1e-11ea-8d0c-45bf00cb3636.png">

However, all requests work on desktop. Here is my **Kernel.php**:

    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class
    ];

Here is my **config/cors.php** file:

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['https://website.com', 'https://m.website.com'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => [],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header with these headers.
     */
    'exposed_headers' => [],

    /*
     * Sets the Access-Control-Max-Age response header when > 0.
     */
    'max_age' => 0,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,
];

I even tried to explicitly set my headers as per this SO answer: 

https://stackoverflow.com/a/52004250

That did not work. Any ideas why iOS browsers are denying my request?

**Comment by barryvdh** [comment]
Can you see the actual OPTIONS request/response headers?

**Comment by i-ira** [comment]
@barryvdh Here is the network call in mobile safari:

<img width="1366" alt="Screen Shot 2020-03-21 at 12 18 08 PM" src="https://user-images.githubusercontent.com/41458922/77231032-b24a2680-6b6e-11ea-823b-2af2b75f435b.png">

As opposed to Safari on desktop:

<img width="1680" alt="Screen Shot 2020-03-21 at 12 18 43 PM" src="https://user-images.githubusercontent.com/41458922/77231133-4d430080-6b6f-11ea-803b-e04e25200e99.png">

same origin of m.website.com.

**Comment by barryvdh** [comment]
But this is the POST right, not OPTIONS?

**Comment by barryvdh** [comment]
To be clear, this is the exact same app? Just a different browser?

**Comment by barryvdh** [comment]
Are you using fetch? With `cors` mode? Or how are you making the request?
Can you mail me to actual app domain?

**Comment by i-ira** [comment]
@barryvdh This is the POST, I don't believe there is a way to view the OPTIONS in Safari. However, In Chrome - here is the OPTIONS:

<img width="1680" alt="Screen Shot 2020-03-21 at 1 58 00 PM" src="https://user-images.githubusercontent.com/41458922/77233236-9b123580-6b7c-11ea-9c6e-3acd25918681.png">

This is the exact same app, which is simply the mobile site (m.website.com) of the main site. All desktop browsers successfully make the POST, however on mobile - specifically iOS, i get the preflight issue.

Unfortunately, I am permitted from sharing the domain with anyone.

**Comment by i-ira** [comment]
**SOLVED:**

Foolishly enough, I failed to realize, in my Nginx config for my desktop site - I had a redirect check for mobile browsers which is why the POST request was failing 😑.

Developer Mental Hiccups. They get the best of us all. Closing now.

**Comment by sanoopborn1994** [comment]
@i-ira Can you please share the Web Configuration you have done for the OPTIONS request ? I have been pulling my hair on this issue for the past three four days. :(

**Comment by herel** [comment]
@sanoopborn1994 
everything worked fine and then I had the same problem

the problem was the / at the end of my route

before:

`export const createIndicator = ({
	name,
	type,
	parent,
	atlas_id,
	id = '',
	color,
	show_time,
	visible,
	legend,
	note,
}) => (dispatch, getState) => {
	const { token } = getState();
	return new Promise((resolve, reject) => {
		axios({
			method: 'POST',
			url: `${API}auth/indicator${id ? `/${id}` : ''}`,`

after:

`export const createIndicator = ({
	name,
	type,
	parent,
	atlas_id,
	id = '',
	color,
	show_time,
	visible,
	legend,
	note,
}) => (dispatch, getState) => {
	const { token } = getState();
	return new Promise((resolve, reject) => {
		axios({
			method: 'POST',
			url: `${API}auth/indicator${id ? `/${id}` : ''}`,`

**Comment by devPinheiro** [comment]
> **SOLVED:**
> 
> Foolishly enough, I failed to realize, in my Nginx config for my desktop site - I had a redirect check for mobile browsers which is why the POST request was failing 😑.
> 
> Developer Mental Hiccups. They get the best of us all. Closing now.

@i-ira Can please share your more details? I'm having a similar issue. Thanks

**Comment by toto1384** [comment]
Any updates on this???
