### ISSUE TITLE
Issue with laravel 7 fresh project

### ISSUE THREAD

**Issue by jamal-rahimzadegan** [fruitcake/laravel-cors#442]
I've created a fresh project which contains this package to pass the cors. I've done all the steps that are mentioned in the documentation but no lock !!!
![2](https://user-images.githubusercontent.com/52101670/78654289-91f1ca00-78d9-11ea-9a81-2288c85955b2.png)
![1](https://user-images.githubusercontent.com/52101670/78654291-93bb8d80-78d9-11ea-82bf-03c50005f211.png)
![2020-04-07_141221](https://user-images.githubusercontent.com/52101670/78654512-d9785600-78d9-11ea-9f6c-282c78e2399a.png)

**Comment by jamal-rahimzadegan** [comment]
I've created a fresh project which contains this package to pass the cors. I've done all the steps mentioned in the documentation but no lock

**Comment by martakielpinska** [comment]
I have the same issue on Laravel 7.4.0. fresh project

**Comment by jamal-rahimzadegan** [comment]
> I've created a fresh project which contains this package to pass the cors. I've done all the steps that are mentioned in the documentation but no lock !!!
> ![2](https://user-images.githubusercontent.com/52101670/78654289-91f1ca00-78d9-11ea-9a81-2288c85955b2.png)
> ![1](https://user-images.githubusercontent.com/52101670/78654291-93bb8d80-78d9-11ea-82bf-03c50005f211.png)
> ![2020-04-07_141221](https://user-images.githubusercontent.com/52101670/78654512-d9785600-78d9-11ea-9f6c-282c78e2399a.png)

I soled it by removing this line: from my request: credentials: "include",
but without it can't upload files to the server

**Comment by denischiciudean** [comment]
Same issue here. Bugging me the entire day

**Comment by barryvdh** [comment]
Did you enable supports_credentials in the config?

**Comment by jamal-rahimzadegan** [comment]
> Did you enable supports_credentials in the config?

according to the docs, it has to be false

**Comment by barryvdh** [comment]
Which docs? If you need cookies/authorization is has to be true.

**Comment by jamal-rahimzadegan** [comment]
> Which docs? If you need cookies/authorization is has to be true.
I need cookies.
I've changed it to true but no lock
 according to this [link](https://packagist.org/packages/barryvdh/laravel-cors)

**Comment by denischiciudean** [comment]
@barryvdh 
`Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost:3000', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

```
/*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['api/*'],

    /*
    * Matches the request method. `[*]` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `[*]` allows all origins.
     */
    'allowed_origins' => ['*'],

    /*
     * Matches the request origin with, similar to `Request::is()`
     */
    'allowed_origins_patterns' => ['*'],

    /*
     * Sets the Access-Control-Allow-Headers response header. `[*]` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header with these headers.
     */
    'exposed_headers' => ['*'],

    /*
     * Sets the Access-Control-Max-Age response header when > 0.
     */
    'max_age' => 0,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => true,`

**Comment by jamal-rahimzadegan** [comment]
it didn't work and gives me this error:
Access to XMLHttpRequest at 'http://localhost:8000/api/login' from origin '
http://localhost:3000' has been blocked by CORS policy: The
'Access-Control-Allow-Origin' header contains multiple values '*,
http://localhost:3000', but only one is allowed.

**Comment by jamal-rahimzadegan** [comment]
solved!!!
1- don't add any of this headers to any controller: 
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: ACCEPT, CONTENT-TYPE, X-CSRF-TOKEN");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE");

2- config your core.php, routes  and post request (fetch) like this photo:

![cors and jwt auth](https://user-images.githubusercontent.com/52101670/78880363-8a155f80-7a6a-11ea-9c2f-07f87da0f3a6.png)

**Comment by barryvdh** [comment]
Yeah don't add your own headers.

**Comment by kenng** [comment]
just to add on, since stumble on this issue for a while, as we are using the passport, so the path in the config need to add, the voila, works like a charm!

```config/cors.php
'paths' => ['api/*', 'oauth/*'],
```

**Comment by AybimYazilim** [comment]
> solved!!!
> 1- don't add any of this headers to any controller:
> header("Access-Control-Allow-Origin: *");
> header("Access-Control-Allow-Headers: ACCEPT, CONTENT-TYPE, X-CSRF-TOKEN");
> header("Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE");
> 
> 2- config your core.php, routes and post request (fetch) like this photo:
> 
> ![cors and jwt auth](https://user-images.githubusercontent.com/52101670/78880363-8a155f80-7a6a-11ea-9c2f-07f87da0f3a6.png)

You saved my day. Thank you!!
