### ISSUE TITLE
Laravel 7 Cors  No 'Access-Control-Allow-Origin' header 

### ISSUE THREAD

**Issue by mohwebs** [fruitcake/laravel-cors#449]
Hi, 
i have a problem with cors and i can't solve it 

![Capture d’écran 2020-04-28 à 07 04 34](https://user-images.githubusercontent.com/45737132/80452614-887ae100-891e-11ea-836f-6cb0508ef0ee.png)

**Cors.php**

![Capture d’écran 2020-04-28 à 07 06 22](https://user-images.githubusercontent.com/45737132/80452740-caa42280-891e-11ea-9b56-90f4fc04b8ab.png)

**api.php**

![Capture d’écran 2020-04-28 à 07 09 28](https://user-images.githubusercontent.com/45737132/80452928-39817b80-891f-11ea-8690-037de7319cb8.png)

**Karnel.php**

`
namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,

        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,

    ];
    
}`

**Comment by barryvdh** [comment]
It looks like you get an error 500?

**Comment by mohwebs** [comment]
@barryvdh yes i get an error 500
like this 
![Capture d’écran 2020-04-28 à 13 22 29](https://user-images.githubusercontent.com/45737132/80486860-c0e8e200-8953-11ea-9f00-567376832730.png)

**can you help me , please?**

**Comment by barryvdh** [comment]
Can you update to the latest version?

**Comment by mohwebs** [comment]
@barryvdh  yes i did ,
i have this with. error 500
![Capture d’écran 2020-04-28 à 13 27 19](https://user-images.githubusercontent.com/45737132/80487078-2210b580-8954-11ea-9c2b-828e06396058.png)

**composer.json**

![Capture d’écran 2020-04-28 à 13 28 48](https://user-images.githubusercontent.com/45737132/80487152-3fde1a80-8954-11ea-9ea7-a6bece6f9e1a.png)

**Comment by barryvdh** [comment]
So can you verify you are on 1.0.6? (Released a few hours ago)

Are there errors in your logs? Does it work when you do the same request with postman?

**Comment by mohwebs** [comment]
@barryvdh  I updated to the latest version but the problem was in JWTSubject in USER model
![Capture d’écran 2020-04-28 à 13 35 41](https://user-images.githubusercontent.com/45737132/80488399-2ccc4a00-8956-11ea-95b8-02f7b21e6609.png)

**No it's work** 
![Capture d’écran 2020-04-28 à 13 40 19](https://user-images.githubusercontent.com/45737132/80488383-22aa4b80-8956-11ea-9935-3b7eebc4c03b.png)


**Thank you so much @barryvdh**

**Comment by thangmam** [comment]
@mohwebs hi you said the problem was in user model.Can you describe in detail please.I have the same problem.using nuxtjs on client side and laravel for backend

**Comment by mohwebs** [comment]
@thangmam  The problem I had not used the libaray in USER Model 
this line -> use Tymon\JWTAuth\Contracts\JWTSubject;

**Comment by dukinfotech** [comment]
> @mohwebs hi you said the problem was in user model.Can you describe in detail please.I have the same problem.using nuxtjs on client side and laravel for backend

Check your User model. I fixed by changing it.

**Comment by itdev-1210** [comment]
Hi,
i have a problem with cors and i can't solve it
![image](https://user-images.githubusercontent.com/54398607/91697079-19025000-eba3-11ea-8411-ccc02038804e.png)

**Cors.php**
![image](https://user-images.githubusercontent.com/54398607/91697133-2fa8a700-eba3-11ea-9888-8666cf2d3136.png)

**Kernel.php**
![image](https://user-images.githubusercontent.com/54398607/91697187-43540d80-eba3-11ea-9091-540e06aa328d.png)

**RouteServiceProvider.php**
![image](https://user-images.githubusercontent.com/54398607/91697293-73031580-eba3-11ea-8263-487adb159575.png)

**Comment by Mupati** [comment]
I faced similar issue with some new endpoints I added. In the end I created my own CORS middleware with the following code.
```
    public function handle($request, Closure $next)
    {
        return $next($request)
            ->header('Access-Control-Allow-Origin', '*')
            ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
            ->header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    }
```
in `kernel.php`  I added
`\App\Http\Middleware\Cors::class,`  to the `protected $middleware` array and  `'cors' => \App\Http\Middleware\Cors::class,`
to the `protected $routeMiddleware` array.

**Comment by Mupati** [comment]
> Hi,
> i have a problem with cors and i can't solve it
> ![image](https://user-images.githubusercontent.com/54398607/91697079-19025000-eba3-11ea-8411-ccc02038804e.png)
> 
> **Cors.php**
> ![image](https://user-images.githubusercontent.com/54398607/91697133-2fa8a700-eba3-11ea-9888-8666cf2d3136.png)
> 
> **Kernel.php**
> ![image](https://user-images.githubusercontent.com/54398607/91697187-43540d80-eba3-11ea-9091-540e06aa328d.png)
> 
> **RouteServiceProvider.php**
> ![image](https://user-images.githubusercontent.com/54398607/91697293-73031580-eba3-11ea-8263-487adb159575.png)

I had a similar issue. I added `'cors' =>  \Fruitcake\Cors\HandleCors::class` to the `$routeMiddleware` in `$Kernel.php`

**Comment by Mupati** [comment]
I added `'cors' =>  \Fruitcake\Cors\HandleCors::class` to the `$routeMiddleware` in `Kernel.php` and the CORS issue was resolved for me.

**Comment by MarFelix** [comment]
> He añadido `'cors' => \Fruitcake\Cors\HandleCors::class`a la `$routeMiddleware`de `Kernel.php`y el problema estaba resuelto CORS para mí.

Tendras la version de Laravel en la que estas trabajando y como están tus archivos Cors.php y Kernel.php Gracias

**Comment by amirkhan402** [comment]
So I tried it in multiple ways, for some versions you have to put cors in kernel.php in:
protected $routeMiddleware = []; 
and for some cases, it works well in:
protected $middleware = [];
