### ISSUE TITLE
CORS paths wildcard and allowed_origins_patterns format 

### ISSUE THREAD

**Issue by perfectdeed** [fruitcake/laravel-cors#451]
Hello. 

I have two quick question.

When I use:
     _'paths' => ['api/*']_
I don't receive the CORS headers.

but using:
     'paths' => ['*']
work as expected. 
Why?

EDIT: Maybe adding in the documentation you can use wildcard in allowed_origin?
That would have saved me some time!

**Comment by IliaMaz** [comment]
@perfectdeed Please look at the readme, carefully.

**Comment by barryvdh** [comment]
Please test with v2 and check if you have any headers added on that routes. Are you using a prefix perhaps?

**Comment by barryvdh** [comment]
The docs were updated.
