### ISSUE TITLE
ErrorException preg_match(): No ending delimiter '*' found

### ISSUE THREAD

**Issue by ajanini** [fruitcake/laravel-cors#453]
I'm running Laravel v7.10.0 and laravel-cors v1.0.6.

It works fine until I try setting the `allowed_origins_patterns` in my config.
As mentioned in https://github.com/fruitcake/laravel-cors/issues/403, I tried adding a wildcard to allow subdomain access, but even using the string mentioned in the issue, I get the error below.

# Config

```
return [

    'paths' => [
        'debug/*',
    ],

    'allowed_methods' => [
        '*',
    ],

    'allowed_origins' => [
        'http://yourdomain.com',
    ],

    'allowed_origins_patterns' => [
        '*.yourdomain.com',
    ],

    // ...
];
```

# Request

Simple GET request to an endpoint in my Laravel app. I am setting an `Origin` header to test CORS.

```
> GET /debug/email HTTP/1.1
> Host: api2.apto.local:7443
> User-Agent: insomnia/7.1.1
> Origin: https://www.disney.com
> Accept: */*
```

# Response Headers
```
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.13.2
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.3.9
< Cache-Control: no-cache, private
< date: Tue, 05 May 2020 17:50:56 GMT
```

# Error

ErrorException
**preg_match(): No ending delimiter '*' found**

<img width="1212" alt="cors-error" src="https://user-images.githubusercontent.com/3225794/81098752-2ef75100-8ee0-11ea-8295-acdc97b121df.png">

# Conclusion

It seems I should use proper `RegEx` instead of the simpler, wildcard-enabled strings similar to the ones used with `Request::is()`, as mentioned in https://github.com/fruitcake/laravel-cors/blob/master/readme.md#configuration, correct?

This seems to work fine:

```
    'allowed_origins_patterns' => [
        '/.*\.yourdomain\.com/',
    ],
```

**Comment by tegola** [comment]
Help here is scarce for being the recommended package in laravel's documentation. I had the same issue, plus I was trying to support local development, so I took a deep dive inside the code.

Turns out you don't need to use a pattern if you only need a wildcard, since the package already converts wildcards in `allowed_origins` to patterns and moves them in `allowed_origins_pattenrs`. So you can just use:

```
'allowed_origins' => ['https://*.mydomain.com'],
```

I need to support local development with Nuxt on `localhost` host, so I'm using:

```
'allowed_origins' => ['https://*.mydomain.com', 'http://localhost:3000'],
```

I'm not even sure whether adding localhost is a bad practice, so I kept the default nuxt port number just in case.

**Comment by barryvdh** [comment]
You are correct, the readme is wrong in this. The wildcard syntax is from allowed_origins is converted to a real pattern. So allow_origins should be an exact match, or wildcard like Request::is(), otherwise use the pattern.

**Comment by barryvdh** [comment]
I've updated the readme. Hopefully it's more clear now.
https://github.com/fruitcake/laravel-cors/commit/7dcfb1a6642a972b10c127aa09ca3172ae4973d5

**Comment by tegola** [comment]
Much clearer, thanks!
