### ISSUE TITLE
CORS Allow Origin '*' not working in production

### ISSUE THREAD

**Issue by refojunior** [fruitcake/laravel-cors#456]
Hi, 
I have an issue with CORS Allowed Origin, why in production server config `'allowed_origins' => ['*']` its  not working. I have to specify the domain to make it works, but in my case I have to allowed any sites to access this. I deploy to heroku. Locally everything work fine, but in production server I have no idea why it's not working. Please help, thank you very much..

**Comment by barryvdh** [comment]
Could you give it a try with v2.0 (just releases) and otherwise show the exact headers etc?

**Comment by carlomigueldy** [comment]
> Could you give it a try with v2.0 (just releases) and otherwise show the exact headers etc?

Wow, I have been waiting for this. Thank you @barryvdh  
I will check it out and let you know how it goes

**Comment by refojunior** [comment]
Header is not present, this is on the client site on production.

![image](https://user-images.githubusercontent.com/30499443/81660579-86ac3400-946d-11ea-84c8-344dd0b189f0.png)


![image](https://user-images.githubusercontent.com/30499443/81660477-62e8ee00-946d-11ea-910b-c0e99ea0dde6.png)


But in local, they are works. See screenshot below..
![image](https://user-images.githubusercontent.com/30499443/81660702-ab081080-946d-11ea-9e5a-5e600d894351.png)

**Comment by barryvdh** [comment]
So what does Vegur do? I also don't see any Origin headers, so not sure how that is made.

**Comment by sachinkiranti** [comment]
> Header is not present, this is on the client site on production.
> 
> ![image](https://user-images.githubusercontent.com/30499443/81660579-86ac3400-946d-11ea-84c8-344dd0b189f0.png)
> 
> ![image](https://user-images.githubusercontent.com/30499443/81660477-62e8ee00-946d-11ea-910b-c0e99ea0dde6.png)
> 
> But in local, they are works. See screenshot below..
> ![image](https://user-images.githubusercontent.com/30499443/81660702-ab081080-946d-11ea-9e5a-5e600d894351.png)
> 
> I'am using your latest version.

@refojunior how did you solved this issue ? I'm getting the same error on production .

**Comment by refojunior** [comment]
@sachinkiranti I fixed this by checking my blade views, some of the Laravel methods didn't work with cors on production. So I remove or rewrite them with pure PHP. I debug this by try to deploy random string/HTML to production, and it works. Then found the problem is in there.
