### ISSUE TITLE
Installation issue con laravel 5.5

### ISSUE THREAD

**Issue by snarchio** [fruitcake/laravel-cors#457]
I'm trying to install via composer (composer 1.10.6, php 7.2, ubuntu 18.04)  but i get this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fruitcake/laravel-cors ^2.0 -> satisfiable by fruitcake/laravel-cors[v2.0.0].
    - Conclusion: remove laravel/framework v5.5.49
    - Conclusion: don't install laravel/framework v5.5.49
    - fruitcake/laravel-cors v2.0.0 requires illuminate/contracts ^5.6|^6.0|^7.0|^8.0 -> satisfiable by illuminate/contracts[5.7.17, 5.7.18, 5.7.19, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/contracts 5.7.17|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts 5.7.18|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts 5.7.19|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.10|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.11|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.15|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.20|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.21|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.22|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.23|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.26|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.27|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.28|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.5|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.6|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.7|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.8|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.7.9|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.10|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.11|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.12|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.13|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.14|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.15|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.16|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.17|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.19|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.20|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.21|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.22|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.23|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.24|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.25|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.26|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.27|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.28|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.29|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.30|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.31|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.32|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.33|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.34|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.35|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.36|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.37|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.38|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.39|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.5|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.6|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.7|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.8|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.6.9|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.11|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.12|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.14|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.15|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.17|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.18|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.19|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.20|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.22|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.24|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.27|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.28|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.29|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.30|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.31|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.32|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.33|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.34|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.35|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.36|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.8|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v5.8.9|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.0.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.0.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.0.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.0.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.0.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.1.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.10.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.11.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.12.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.13.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.13.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.14.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.15.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.15.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.16.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.17.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.17.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.10|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.11|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.12|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.13|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.5|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.6|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.7|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.8|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.18.9|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.2.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.3.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.4.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.5.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.5.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.5.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.6.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.6.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.6.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.7.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v6.8.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.4|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.5|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.6|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.7|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.0.8|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.1.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.1.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.1.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.1.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.10.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.10.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.10.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.10.3|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.2.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.2.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.2.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.3.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.4.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.5.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.5.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.5.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.6.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.6.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.6.2|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.7.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.7.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.8.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.8.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.9.0|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.9.1|don't install laravel/framework v5.5.49
    - don't install illuminate/contracts v7.9.2|don't install laravel/framework v5.5.49
    - Installation request for laravel/framework (locked at v5.5.49, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.49].

Installation failed, reverting ./composer.json to its original content.

Composer decides that laravel/framework is not necessary and of course all fails.
I read that similar issues were present in previous releases but were fixed.

Any advice?

**Comment by barryvdh** [comment]
Use 1.x for Laravel 5.5.
