### ISSUE TITLE
Composer failed on a fresh Laravel build

### ISSUE THREAD

**Issue by adicle** [fruitcake/laravel-cors#458]
Just came to install this on a fresh Laravel 7 build and got these errors:

**Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install fruitcake/laravel-cors v2.0.0
    - Conclusion: don't install fruitcake/laravel-cors v2.0.0-beta3
    - Conclusion: don't install fruitcake/laravel-cors v2.0.0-beta2
    - Conclusion: don't install fruitcake/laravel-cors v2.0.0-beta1
    - Conclusion: remove asm89/stack-cors 1.3.0
    - Installation request for fruitcake/laravel-cors ^2.0 -> satisfiable by fruitcake/laravel-cors[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3].
    - Conclusion: don't install asm89/stack-cors 1.3.0
    - fruitcake/laravel-cors 2.0.x-dev requires asm89/stack-cors ^2 -> satisfiable by asm89/stack-cors[2.0.0, 2.0.0-beta1, 2.0.0-beta2, 2.0.0-beta3, 2.0.x-dev].
    - Can only install one of: asm89/stack-cors[2.0.0, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta1, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta2, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta3, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.x-dev, 1.3.0].
    - Installation request for asm89/stack-cors (locked at 1.3.0) -> satisfiable by asm89/stack-cors[1.3.0].

Installation failed, reverting ./composer.json to its original content.**

Does anyone know the best way to solve this?

**Comment by tore99** [comment]
Same problem with Laravel 7

**Comment by barryvdh** [comment]
Did you already install a previous version? Like barryvdh/laravel-cors? Or can you run `composer why asm89/stack-cors` to see why it wants to install 1.3 still.

**Comment by tore99** [comment]
```
$ composer why asm89/stack-cors
fruitcake/laravel-cors  v1.0.6  requires  asm89/stack-cors (^1.3)
```
did not specify the reason

**Comment by barryvdh** [comment]
What if you remove it fruitcake/laravel-cors and then require again? Seems it's already installed v1 but not sure why it wouldn't update that.

**Comment by tore99** [comment]
Ok, it works! 
Yes, it's already installed and don't update it.

some errors when run 
`composer remove fruitcake / laravel-cors`
```
Dependency "laravel / framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel / framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 2 removals
  - Removing fruitcake / laravel-cors (v1.0.6)
  - Removing asm89 / stack-cors (1.3.0)
Writing lock file
Generating optimized autoload files
> Illuminate \ Foundation \ ComposerScripts :: postAutoloadDump
> @php artisan package: discover --ansi
Discovered Package: facade / ignition
Discovered Package: fideloper / proxy
Discovered Package: laravel / tinker
Discovered Package: laravel / ui
Discovered Package: nesbot / carbon
Discovered Package: nunomaduro / collision
Package manifest generated successfully.
```
...but then run `composer require fruitcake/laravel-cors` and works!
Thank you!!!

**Comment by dangminhtruong** [comment]
Same problem with Laravel 7

**Comment by barryvdh** [comment]
Same solution also?

**Comment by SalehMahmood** [comment]
For anyone whos facing the same issue while upgrading from an older Laravel version, I solved mine by running the following commands
```
$ composer why asm89/stack-cors
barryvdh/laravel-cors  v0.11.4  requires  asm89/stack-cors (^1.2)
$ composer remove  barryvdh/laravel-cors
...
$ composer require fruitcake/laravel-cors --prefer-dist
...
```
Also removed `\Barryvdh\Cors\HandleCors::class,` from middleware.

**Comment by itwondersteam** [comment]
work after uninstall and install again!

**Comment by brianzzzasd** [comment]
This works for me

`composer remove fruitcake/laravel-cors`
`composer require asm89/stack-cors "2.0.0"`
`composer require fruitcake/laravel-cors "2.0.0"`

**Comment by barryvdh** [comment]
Yeah don't do that. Just remove it and require fruitcake/laravel-cors 2.x, not stack cors and not 2.0.0, because now you're fixed on a single version.

**Comment by 949mac** [comment]
Remove and reinstall with `composer require fruitcake/laravel-cors --prefer-dist` worked for me

**Comment by angellcantu** [comment]
@brianzzzasd great solution!

**Comment by kfazil** [comment]
Thanks for the solution @barryvdh 👍

**Comment by shawon3719** [comment]
@brianzzzasd Great Man! It works. 👍

**Comment by placecodex** [comment]
this worked for me 

composer remove barryvdh/laravel-cors fruitcake/laravel-cors
composer require fruitcake/laravel-cors

**Comment by Whax** [comment]
the @tore99 worked for me too ;)

**Comment by Risfan0109** [comment]
great solution, thanks

**Comment by thalesbarbosab** [comment]
> This works for me
> 
> `composer remove fruitcake/laravel-cors`
> `composer require asm89/stack-cors "2.0.0"`
> `composer require fruitcake/laravel-cors "2.0.0"`

**Comment by antony0592** [comment]
> > This works for me
> > `composer remove fruitcake/laravel-cors`
> > `composer require asm89/stack-cors "2.0.0"`
> > `composer require fruitcake/laravel-cors "2.0.0"`

Work for me
