### ISSUE TITLE
RuntimeException CORS config allowed_origins should be an array

### ISSUE THREAD

**Issue by niyazmv** [fruitcake/laravel-cors#459]
Works perfectly fine in windows environment but does not work on Ubuntu 18.07 LTS Nginx server 
keep throwing that Runtime exception allowed_origins should be an array

I am using the default config :
    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['*'],

    /*
    * Matches the request method. [*] allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. [*] allows all origins. Wildcards can be used, eg *.mydomain.com
     */
    'allowed_origins' => ['*'],

    /*
     * Patterns that can be used with preg_match to match the origin.
     */
    'allowed_origins_patterns' => [],

    /*
     * Sets the Access-Control-Allow-Headers response header. [*] allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header with these headers.
     */
    'exposed_headers' => [],

    /*
     * Sets the Access-Control-Max-Age response header when > 0.
     */
    'max_age' => 0,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,

**Comment by niyazmv** [comment]
> Works perfectly fine in windows environment but does not work on Ubuntu 18.07 LTS Nginx server
> keep throwing that Runtime exception allowed_origins should be an array
> 
> I am using the default config :
> /*
> * You can enable CORS for 1 or multiple paths.
> * Example: ['api/*']
> _/ 'paths' => ['_'],
> 
> ```
> /*
> * Matches the request method. [*] allows all methods.
> */
> 'allowed_methods' => ['*'],
> 
> /*
>  * Matches the request origin. [*] allows all origins. Wildcards can be used, eg *.mydomain.com
>  */
> 'allowed_origins' => ['*'],
> 
> /*
>  * Patterns that can be used with preg_match to match the origin.
>  */
> 'allowed_origins_patterns' => [],
> 
> /*
>  * Sets the Access-Control-Allow-Headers response header. [*] allows all headers.
>  */
> 'allowed_headers' => ['*'],
> 
> /*
>  * Sets the Access-Control-Expose-Headers response header with these headers.
>  */
> 'exposed_headers' => [],
> 
> /*
>  * Sets the Access-Control-Max-Age response header when > 0.
>  */
> 'max_age' => 0,
> 
> /*
>  * Sets the Access-Control-Allow-Credentials header.
>  */
> 'supports_credentials' => false, 
> ```

i fix my issue it was problem with permission issue , if anyone come up with this error make sure the directory has www-data permission 
Thanks

**Comment by albalooshi** [comment]
I solved by it by running
```
php artisan cache:clear
php artisan config:clear
```

**Comment by farhan1204110** [comment]
Thank you!

> I solved by it by running
> 
> ```
> php artisan cache:clear
> php artisan config:clear
> ```
