### ISSUE TITLE
Request header field not allowed

### ISSUE THREAD

**Issue by artmerlop** [fruitcake/laravel-cors#460]
**Request code**

```
import axios from 'axios'
import {endPoint} from '../common'
export default {
  request(method, uri, data = null, options, type, newHeaders) {
    if (!method) return
    if (!uri) return
    var headers = {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'X-Requested-With': 'XMLHttpRequest'
    }
    if (newHeaders) {
      Object.assign(headers, newHeaders)
    }
    var url = uri.indexOf('http') > -1 ? uri : endPoint + uri
    var req = {method, url, data, options, headers}
    if (type === 'blob') {
      req = {method, url, data, options, responseType: 'blob', headers}
    }
    return axios(req)
  }
}
```

**CORS config setup**

```
return [
    'paths' => ['api/*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => false,
];
```

**Kernel middleware setup**

```
protected $middleware = [
   // \App\Http\Middleware\TrustHosts::class,
   \App\Http\Middleware\TrustProxies::class,
   \Fruitcake\Cors\HandleCors::class,
   \App\Http\Middleware\CheckForMaintenanceMode::class,
   \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
   \App\Http\Middleware\TrimStrings::class,
   \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
 ];
```

**More info**

All permissions are okay, and the setup is fine, but the request doesn't pass , if a send it without headers it works, but if I add headers to my axios request I get the following error in Safari:

[Error] Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

And in Chrome I get:

[Error] Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.

I have the latest version 2.0.0, and Laravel Framework 7.0, I've tried with fresh Laravel projects and they doesn't work either.

**Comment by barryvdh** [comment]
And with `'*'` as path?

**Comment by artmerlop** [comment]
@barryvdh same error.

**Comment by barryvdh** [comment]
And if you list the headers explicitly instead of *?

**Comment by artmerlop** [comment]
@barryvdh just tried, same error.

**Comment by artmerlop** [comment]
Also I tried removing paths to see if I got a different error and verify that the provider was applying, and I did get a different error:

[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.

**Comment by barryvdh** [comment]
Can you share your request and response headers? Most importantly

**Comment by barryvdh** [comment]
I've tried to recreate it here: https://github.com/fruitcake/laravel-cors/pull/462
But not sure why it wouldn't work for you.

**Comment by artmerlop** [comment]
@barryvdh I just get this.

<img width="590" alt="Captura de Pantalla 2020-05-21 a la(s) 1 44 41" src="https://user-images.githubusercontent.com/50642674/82691243-34180800-9c23-11ea-8971-493782969dec.png">

**Comment by artmerlop** [comment]
I've tried everything and I can't solve this yet...

**Comment by woutervu** [comment]
@artmerlop I too had the same issue you're describing. I was using version ^2.0.0. Reverting back to version ^1.0.0 "fixed" the problem for me.

I don't have time right now to look into the problem, but this might be a good starting point to start working towards a fix.

**Comment by barryvdh** [comment]
@artmerlop van you test with 1.x?

**Comment by barryvdh** [comment]
Are cookies being sent with the request? In that case, * might not be valid. Bot listing the headers should still work :/ https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

**Comment by barryvdh** [comment]
If you can, can you try it with v2.0.1?

**Comment by grEvenX** [comment]
@barryvdh I can confirm that 2.0.1 at least solved a similar issue for us

**Comment by barryvdh** [comment]
@artmerlop Can you test with 2.0.1?

**Comment by artmerlop** [comment]
@barryvdh yes! It now works in version 2.0.1
