### ISSUE TITLE
Exceptions are not including CORS headers despite having HandleCors defined in the global middleware stack

### ISSUE THREAD

**Issue by KieronWiltshire** [fruitcake/laravel-cors#468]
**Issue**

I make a request to my routes. If the request is all good and no exceptions are thrown then it responds okay. However, if a request throws an exception, the headers aren't being attached to the response despite having HandleCors defined in the global middleware stack.

**Before you start**

[ X ] Update to the latest version by running `composer update fruitcake/laravel-cors`
[ X ] Make sure that Apache/nginx/Valet are NOT also adding CORS headers

**Check your config**

[ X ]  Double-check your config file with the version from the repo. Make sure the `paths` property is correctly set. Start by allowing as much as possible.
[ X ]  Make sure the middleware is added to the global middleware in your Http Kernel (not group)

**Clear your caches**

Please do these steps again before submitting an issue:
[ X ]  Clear your config cache `php artisan config:clear`, route cache (`php artisan route:clear`) and normal cache (`php artisan cache:clear`).
[ X ]  Make sure your permissions are setup correctly (eg. storage is writable)

**Make the request**

Open Chrome Devtools to see which requests are actually happening. Make sure you see the actual OPTIONS requests for POST/PUT/DELETE (see https://stackoverflow.com/questions/57410051/chrome-not-showing-options-requests-in-network-tab)

Please show the actual request + response headers as sent by the OPTIONS request and the POST request (when available)

Below is an example of the request working fine:
![image](https://user-images.githubusercontent.com/4332346/84069031-cbba7c00-a9c1-11ea-855a-0ccaec1ad8c8.png)

Below is an example of the request failing:
![image](https://user-images.githubusercontent.com/4332346/84069291-38357b00-a9c2-11ea-879a-162832ef4db6.png)
![image](https://user-images.githubusercontent.com/4332346/84069535-906c7d00-a9c2-11ea-9f99-77cf1ce1b739.png)

Below is proof that it's defined in the middleware stack:
![image](https://user-images.githubusercontent.com/4332346/84069373-54d1b300-a9c2-11ea-9693-dc322227c035.png)

**Comment by barryvdh** [comment]
What kind of exception is it? How are you throwing it?

**Comment by KieronWiltshire** [comment]
@barryvdh simply by throwing the exception from the controllers. I want to add this all worked fine with Spatie's version of Cors, I had no issues. I remove Spatie's version when I was upgrading to Laravel 7 and followed the upgrade guidelines.

**Comment by barryvdh** [comment]
So Laravel 7? I tried to replicate it in the tests but will give it another try.

**Comment by KieronWiltshire** [comment]
@barryvdh I’m more than happy to show you over a call, but unwilling to put any of the code here for business reasons

**Comment by barryvdh** [comment]
I understand that. Maybe you could share the ExceptionHandler with me? Do you override anything? Does moving the middleware to the top change anything?

**Comment by barryvdh** [comment]
And it's not the dd() that is reached right?

**Comment by KieronWiltshire** [comment]
You know what... thinking about it, it might be. I will have to confirm this, if that is the case I’ll close this issue.

**Comment by kevin1193** [comment]
This happened to me too. My custom exceptions were having CORS issue.

**Comment by ajarti** [comment]
You can replicate this issue with a clean install of Laravel .. just trigger a dd .. when accessing via axios on a separate domain and bang 
```
Access to XMLHttpRequest at '[the_endpoint]' from origin '[the_spa]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I spent days trying to configure CORS and realised it's just not sending the header if an error occurs on the server .. or you trigger dd() .. which I use heavily.

Just using the log for now .. not very elegant .. but no time to track down.

**Comment by barryvdh** [comment]
Yeah you can't use dd(), See https://github.com/fruitcake/laravel-cors#echodie

**Comment by barryvdh** [comment]
So it was dd?

**Comment by ajarti** [comment]
Nope in my instance it was an unhandled exception,  but I was on a wild goose chase for quite a while .. lol until I realised nothing was wrong with CORS.

Still trying to work around the no dd issue. I use it quite heavily to dump objects .. but it is what it is.

Thanks for the heads up Barry :)  and thanks for a great package.

**Comment by KieronWiltshire** [comment]
> So it was dd?

ye

**Comment by ajarti** [comment]
I make use of dd often to dump/inspect objects that may be deeper than a controller such as in a repository class, so there is no way to elegantly return them with out upsetting CORS as mentioned.  A simple solution, albeit hacky, is to make a global function that just wraps dd() and adds the headers before dying.

1. Make a file app/Helper/global.php and in this file place. 
```php
<?php

if (!function_exists('cors_dd')) {
    /**
     * Wrap dd() and inject required CORS headers first.
     * 
     * @param  null  $var  // Just so we have a default value.
     */
    function cors_dd($var = null)
    {

        // Send the required CORS headers.
        $origin = $_SERVER['HTTP_ORIGIN'] ?? '*';
        header("Access-Control-Allow-Origin: $origin");
        header('Access-Control-Allow-Credentials: true'); // Only needed if you are using Sanctum.

        // DD the var.
        dd($var);
    }
}
```

Then in your composer.json add a "files" section to the "autoload-dev" section. 
```JSON
 "autoload-dev": {
        "files": [
            "app/Helpers/global.php"
        ],
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
```

To have the function auto loaded.  Then just use 
```php
cors_dd($object);
```
to dump your $objects.

I am sure there are way more elegant methods .. but this is simple and does the job .. just thought it might help someone else.
