### ISSUE TITLE
CORS Allowing Everything even if allowed_origins is set to a specific URL 

### ISSUE THREAD

**Issue by dryaner** [fruitcake/laravel-cors#473]
The new cors plugin is not checking the allowed origins. with version 0.x was working properly. I checked that the configuration is passing through. but  The new version is missing this code in HandleCors.php handle function:
  

       if (! $this->cors->isActualRequestAllowed($request)) {  
            return new LaravelResponse('Not allowed in CORS policy.', 403);
        }

And the function isOriginAllowed in stack-cors -> corsService.php is never called.

I don't know if i'm missing something or if it's a bug.

Kernel.php
  
    protected $middleware = [
        \Fruitcake\Cors\HandleCors::class,
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
    ];

cors.php
  
    'paths' => ['api/*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['http://test-site.local'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => false,

request header
![image](https://user-images.githubusercontent.com/4254685/84664493-a14e4e80-aeec-11ea-845a-2c55bceb637c.png)

response header

![image](https://user-images.githubusercontent.com/4254685/84664557-b6c37880-aeec-11ea-9262-e7314ebf3d4f.png)

**Comment by barryvdh** [comment]
Postman doesn't apply CORS, your browser does. Because the allowed origin does not match, it will prevent execution. (CORS is not for backend security, because you can just omit/fake the Origin header with Postman)
