### ISSUE TITLE
Clarification in readme

### ISSUE THREAD

**Issue by Krisell** [fruitcake/laravel-cors#474]
The readme says the following:

```makrdown
# Disabling CSRF protection for your API

If possible, use a different route group with CSRF protection enabled. Otherwise you can disable CSRF for certain requests in App\Http\Middleware\VerifyCsrfToken:
```

Is this a typo, and should read, "CSRF protection *disabled*", or am I missing something? Also, it's not overly clear how this section relates to the package (especially since people sometimes confuse CSRF and CORS), but I'm guessing it's general advice for API-routes, which are closely related to this package?

**Comment by barryvdh** [comment]
Yes should be disabled indeed.

**Comment by Krisell** [comment]
Thanks, my brain is now a lot less confused! :)
