### ISSUE TITLE
CORS wrongly-passing when allowed_origins set

### ISSUE THREAD

**Issue by MrWeb** [fruitcake/laravel-cors#482]
I have CORS setup in the config to allow `allowed_origins` only from a certain site.

```
    'paths'                    => ['api/*'],
    'allowed_methods'          => ['*'],
    'allowed_origins'          => ['https://portal.mysite.com'],
    'allowed_origins_patterns' => [],
    'allowed_headers'          => ['*'],
    'exposed_headers'          => [],
    'max_age'                  => 0,
    'supports_credentials'     => false,
```

I wanted to test this functionality and I opened up my RestAPI Client, Insomnia.
I make a call to the local domain `http://mysite.test/api/login` and I get in return a correct 200 server response instead of blocking my request.

Setup:

- Valet on local machine with site working at `http://mysite.test/api/`
- Local Insomnia app sending a POST request to `http://mysite.test/api/login`

The result: a 200 server code response
The expected result: a blockage of the request because I'm sending from local but the allowed origin is `https://portal.mysite.com` only

**Comment by barryvdh** [comment]
CORS blocks client side in the browser, it's no firewall.
