### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by imtrent** [fruitcake/laravel-cors#486]
I'm running into the problem below every time I make an API request using axios. 

> Access to XMLHttpRequest at 'http://localhost:8000/api/v1/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am running Laravel 7 through Laravel homestead which uses nginx. I am using `"fruitcake/laravel-cors": "^2.0"` and have also tried version 2.0.1.  After looking around at related issues, I believe the problem lies with the package and nginx. My requests also work perfectly fine on postman.

I have tried `php artisan cache:clear` but that does not fix the issue.

config/cors.php
```php
[
    'paths' => ['api/*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true
]
```

app/Http/Kernal.php
```php
protected $middleware = [
    \Fruitcake\Cors\HandleCors::class,
    \App\Http\Middleware\TrustProxies::class,
    \App\Http\Middleware\CheckForMaintenanceMode::class,
    \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
    \App\Http\Middleware\TrimStrings::class,
    \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
];
```

Axios configuration
```javascript
export const apiRoute = 'http://localhost:8000/api/v1/';
export default axios.create({
    withCredentials: true,
    baseURL: apiRoute
});
```

**Comment by imtrent** [comment]
I was able to figure out the issue. It had nothing to do with CORS but was throwing a CORS error. I had some code in the render function of app>Exceptions>Handler.php that was breaking the API requests.

**Comment by vgavrilovikj** [comment]
@imtrent How does your Handler.php look like?
