### ISSUE TITLE
Laravel 7 CORS ISSUE

### ISSUE THREAD

**Issue by itdev-1210** [fruitcake/laravel-cors#493]
Hi,
i have a problem with cors and i can't solve it
![image](https://user-images.githubusercontent.com/54398607/91697079-19025000-eba3-11ea-8411-ccc02038804e.png)

**Cors.php**
![image](https://user-images.githubusercontent.com/54398607/91697133-2fa8a700-eba3-11ea-9888-8666cf2d3136.png)

**Kernel.php**
![image](https://user-images.githubusercontent.com/54398607/91697187-43540d80-eba3-11ea-9091-540e06aa328d.png)

**RouteServiceProvider.php**
![image](https://user-images.githubusercontent.com/54398607/91697293-73031580-eba3-11ea-8263-487adb159575.png)

**Comment by itdev-1210** [comment]
@barryvdh please help

**Comment by KieronWiltshire** [comment]
I also share this issue and so do many others, why is this not fixed yet? @barryvdh

**Comment by barryvdh** [comment]
Please submit a pull request with either a fix or a failing test so I can reproduce.

**Comment by KieronWiltshire** [comment]
@barryvdh actually, my bad... I was sending a request to AWS Route 53 on HTTP which was returning a 301 to HTTPS (without CORS). Rebuilding my front-end to use HTTPS scheme fixed my issue, I suspect this will be a common issue.

**Comment by itdev-1210** [comment]
Not Laravel 7 Issue.
I had tried to call with this URI (HTTP://localhost:85/api/login/)
Change it to HTTP://localhost:85/api/login
I'm not sure what are differents.
Btw, it works in my side.
@barryvdh, if you have any advice, please leave comment.

**Comment by stojankukrika** [comment]
the same issue I have..in localhost works all but when release app on the server didn't work anymore;(
