### ISSUE TITLE
Laravel 8 Cors not working

### ISSUE THREAD

**Issue by danbdex** [fruitcake/laravel-cors#504]
Hi I have done all the "before you start tasks and checks"
Error in cosole log:

> Access to fetch at 'http://127.0.0.1:8000/register' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Network Request:
![image](https://user-images.githubusercontent.com/16898938/95819338-acd84780-0d1d-11eb-8aa2-cef22f35675f.png)

\config\cors.php
```
return [

    'paths' => ['api/*', 'register', 'oauth/*'],
    'allowed_methods' => ['OPTIONS,POST,PUT,DELETE,GET'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => ['*'],
    'max_age' => 0,
    'supports_credentials' => true,
];
```
Kernel.php
 ```
  protected $middleware = [

        \Fruitcake\Cors\HandleCors::class,

```

I have tried as many combinations of the above as I can spent about 6 hours on it now with no success, your help would be greatly appreciated.

thanks

Dan

**Comment by danbdex** [comment]
I built a new Laravel app and copied over all the code and it worked.

**Comment by trainoasis** [comment]
@danbdex did you figure what the issue was exactly? I have CORS issues for 2 days now, Axios gets 200 response and data from Laravel, but error is returned about the CORS headers missing and catch block is fired so I can get the data normally (but i see the data inside the xhr request in dev tools). I have the same Kernel.pohp and cors.php as you above ...

**Comment by itzmj-23** [comment]
I also encountered the same issue, upgraded from Laravel 5.7 to 7.x. It seems after upgrading it is not automatically added to the project folder. 

So, I added `composer require fruitcake/laravel-cors ` and `protected $middleware = [
  \Fruitcake\Cors\HandleCors::class,
    // ...
];` in `app/Http/Kernel.php` and also created `cors.php` inside `config folder`.

**config file**

    return [
        'paths' => ['api/*'],
        'allowed_methods' => ['*'],
        // 'allowed_origins' => ['http://127.0.0.1:8080/', 'http://localhost:8080/'], <-- doesn't work, still gets CORS error
        'allowed_origins' => ['*'],  // <-- it works but it should not be like that
        'allowed_origins_patterns' => [],
        'allowed_headers' => ['content-type', 'accept', 'x-custom-header', 'Access-Control-Allow-Origin'],
        // 'allowed_headers' => ['*'],
        'exposed_headers' => ['x-custom-response-header'],
        'max_age' => 0,
        'supports_credentials' => false,
    ];

So, I am still wondering how it works completely. Any insight is appreciated.

**Comment by xavsio4** [comment]
Same problem, it seems like the config/Cors file is totally ignore even though I've puged the cache (php artisan config:cache)

**Comment by xavsio4** [comment]
Ok, some things here. I'm using Nuxt as a client and I there was a part of my url that was missing '/api/'. So it looks like when there is a mistake in the url you get the cors response. But that does not explains all, after correcting the url i'd get the same error. So I commented out the fruitcake middleware part of the kernel.file and added one cors file found somewhere...but not using the provided cors extension. That still did not the trick. So, i've found on stackoverflow this piece of code 
`header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: Origin, X-Requested-With,Authorization,  Content-Type, Accept');
`
that I've added at the top of the app.php file inside the bootstrap folder. And that made it work. It was a fresh install with passport.

**Comment by rishirajpurohit** [comment]
anyone coming here, please try `php artisan config:cache` after any changes. That was the problem with my setup. may it save you few hours.

**Comment by Adeel321123** [comment]
I am using vue.js separate web app reset API are written in laravel 8. no I fix this issue by adding `api` in the base URL of Axios request
from
baseURL: 'http://localhost/adeel/backend-modesy'
to 
baseURL: 'http://localhost/adeel/backend-modesy/api'
it's working for me

**Comment by kumaranup594** [comment]
You can add into TrustHosts.php Middleware without doing anything extra.
```php
// app/Http/Middleware/TrustHosts.php
public function hosts()
{
    return [
        $this->allSubdomainsOfApplicationUrl(),
        'https://www.nexgi.com'
    ];
}
```
The above code is working well in laravel 8.x and if you are running queue or supervisorctl then restart to reflect the changes.

**Comment by yourikoeman** [comment]
Adding to this: the cors headers are sent on the way back up the middleware stack, if you have any debug & die/ flow breaks in your controllers or any other place before the stack, the headers will not be added.

**Comment by Ham3D** [comment]
> anyone coming here, please try `php artisan config:cache` after any changes. That was the problem with my setup. may it save you few hours.

wasted 3 hours here ....
also tried clearing config cache and still no success.
thanks \m/

**Comment by folkevil** [comment]
> > anyone coming here, please try `php artisan config:cache` after any changes. That was the problem with my setup. may it save you few hours.
> 
> wasted 3 hours here .... also tried clearing config cache and still no success. thanks \m/

same to me, try to config in both Laravel and nginx but no luck

**Comment by melaskotingo** [comment]
I was doing the same error with angular. I switch from next to laravel backend and forgot to add /api to the api url. Thank u. You save me a lot of time of debugging

**Comment by jordanharding** [comment]
I had this same issue, config cache wasn't it, I cleared all caches and the issue was then resolved

https://beyondco.de/blog/laravel-caches-and-all-ways-to-clear-them

**Comment by jatinbphp** [comment]
None of above solutions works for me.
Have laravel 8 and vue js.

**Comment by Ham3D** [comment]
> None of above solutions works for me.
> Have laravel 8 and vue js.

Check your logs, there are times that there is a 500 problem but laravel shows cors( the cors config are not loaded yet) problem

**Comment by patforg** [comment]
To fix this problem I had to add a path to my cors.php

I changed:
`   'paths' => [],`
to:
`   'paths' => ['/'],`

**Comment by musznik** [comment]
dont forget about apache module **LoadModule headers_module modules/mod_headers.so**

**Comment by AkashTtyagi** [comment]
To Fix this problem I had run this command 

sudo php artisan config:cache

**Comment by BenceBakos** [comment]
For `bitnami/laravel/` docker user who wants to add CORS header to static resources(images in my case):
No hope folks, dirty workarounds are the only solutions :S  

I tought somehow I can change nginx/apache configuration, but it turns out that this image uses the following artisan command:
```
php artisan serve --host=0.0.0.0 --port=8000
```

And I find no options to add CORS headers.


Note:
For php related url-s, the following solutions will work:

**config/cors.php**
Update `config/cors.php`, then run `php artisan config:cache`

**headers in index.php**
Add the following lines to `public/index.php`:
```
header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
header('Access-Control-Allow-Headers: content-type');
```

**Comment by kohilan-hub** [comment]
Add this into your .htaccess which is located in public with your index.php
Code:
    ## For CORS Configuration

    # Add Font Types
    AddType application/vnd.ms-fontobject .eot
    AddType application/x-font-ttf        .ttf
    AddType application/x-font-opentype  .otf
    AddType application/font-woff        .woff
    AddType application/font-woff2        .woff2

    <IfModule mod_headers.c>
        <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg|svgz|jpg|png|ico|font.css|css|js)$">
            ## un-remark this one for all access and remark out the one below it

**Comment by kohilan-hub** [comment]
Add this into your .htaccess which is located with your index.php
Code:
   ## For CORS Configuration

    # Add Font Types
    AddType application/vnd.ms-fontobject .eot
    AddType application/x-font-ttf        .ttf
    AddType application/x-font-opentype  .otf
    AddType application/font-woff        .woff
    AddType application/font-woff2        .woff2

    <IfModule mod_headers.c>
        <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg|svgz|jpg|png|ico|font.css|css|js)$">
            ## un-remark this one for all access and remark out the one below it
            #Header set Access-Control-Allow-Origin "*"
            ## Change this to your local host url. and https or http
            Header add Access-Control-Allow-Origin: "https://typeHEREyour.com"
            Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
            Header add Access-Control-Allow-Headers: "Upgrade-Insecure-Requests"
        </FilesMatch>
    </IfModule>

    # Remove index.php from URL
    RewriteCond %{HTTP:X-Requested-With}    !^XMLHttpRequest$
    RewriteCond %{THE_REQUEST}              ^[^/]*/index\.php [NC]
    RewriteRule ^index\.php(.*)$            $1 [R=301,NS,L]

**Comment by RyanSacks** [comment]
> I also encountered the same issue, upgraded from Laravel 5.7 to 7.x. It seems after upgrading it is not automatically added to the project folder.
> 
> So, I added `composer require fruitcake/laravel-cors ` and `protected $middleware = [ \Fruitcake\Cors\HandleCors::class, // ... ];` in `app/Http/Kernel.php` and also created `cors.php` inside `config folder`.
> 
> **config file**
> 
> ```
> return [
>     'paths' => ['api/*'],
>     'allowed_methods' => ['*'],
>     // 'allowed_origins' => ['http://127.0.0.1:8080/', 'http://localhost:8080/'], <-- doesn't work, still gets CORS error
>     'allowed_origins' => ['*'],  // <-- it works but it should not be like that
>     'allowed_origins_patterns' => [],
>     'allowed_headers' => ['content-type', 'accept', 'x-custom-header', 'Access-Control-Allow-Origin'],
>     // 'allowed_headers' => ['*'],
>     'exposed_headers' => ['x-custom-response-header'],
>     'max_age' => 0,
>     'supports_credentials' => false,
> ];
> ```
> 
> So, I am still wondering how it works completely. Any insight is appreciated.

Is this package for API routes only?
