### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by jud3v** [fruitcake/laravel-cors#508]
**Before you start**

[✅] Update to the latest version by running `composer update fruitcake/laravel-cors`
[✅] Make sure that Apache/nginx/Valet are NOT also adding CORS headers

**Check your config**

[✅]  Double-check your config file with the version from the repo. Make sure the `paths` property is correctly set. Start by allowing as much as possible.
[✅]  Make sure the middleware is added to the global middleware in your Http Kernel (not group)

**Clear your caches**

Please do these steps again before submitting an issue:
[✅]  Clear your config cache `php artisan config:clear`, route cache (`php artisan route:clear`) and normal cache (`php artisan cache:clear`).
[✅]  Make sure your permissions are setup correctly (eg. storage is writable)
I have chmod -R 777 the `storage` so I think the storage are writable.

**Version production tested**
- Laravel: 8.11.x
- Fruitcake/laravel-cors: 2.0.2, 2.0.3
- php: 7.3.x
- nginx: nginx/1.14.2

**My cors configuration tested: ( this conf only work with get request see the second image )**
```php
return [

    'paths' => ['api/*'],

    'allowed_methods' => ['GET, POST, PUT, PATCH, DELETE, OPTIONS'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,

];
```

**tested with the default conf: ( not work with any request )**
```php

return [

    'paths' => ['api/*'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,

];
```

**Brief description**
> If I make a `GET` request with the personal cors conf, the request will be executed well.

> But if I make a post request to the register, the cors does not allow my request, I don't know if I have miss anything are if I have a bad configuration.

> I have try to see the options request without success.

**Images**
[![Capture-d-cran-2020-10-26-13-47-14.png](https://i.postimg.cc/MKk3tjsc/Capture-d-cran-2020-10-26-13-47-14.png)](https://postimg.cc/F1ZxH1Xm)
[![Capture-d-cran-2020-10-26-13-47-31.png](https://i.postimg.cc/5yW558xb/Capture-d-cran-2020-10-26-13-47-31.png)](https://postimg.cc/ZBjy4BBM)
[![Capture-d-cran-2020-10-26-13-47-54.png](https://i.postimg.cc/66VCJ2W4/Capture-d-cran-2020-10-26-13-47-54.png)](https://postimg.cc/Z0RW6qyJ)
[![Capture-d-cran-2020-10-26-13-58-32.png](https://i.postimg.cc/3wDDLWfR/Capture-d-cran-2020-10-26-13-58-32.png)](https://postimg.cc/DWnZ0fTk)

I'm using at frontend React this as the address: `https://bao-bab.fr`
And I have my backend on Laravel: `https://web-srv1-bao-bab.com/api/auth/register`

I have already try to add my front addresses to the `allowed_origins`but that don't work;
I have try to to add the header to my Nginx configuration.

**Nginx Conf for backend**
```
server {
    server_name web-srv1-bao-bab.com;
    root /var/www/baobab/backend/public;     

    index index.php;

    charset utf-8;
      
    location / {
        try_files $uri $uri/ /index.php?$query_string;

    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/web-srv1-bao-bab.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/web-srv1-bao-bab.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    listen 443;
    server_name web-srv1-bao-bab.com;
    root /var/www/baobab/backend/public; 

    index index.php;

    charset utf-8;
   
    location / {
        try_files $uri $uri/ /index.php?$query_string;
           
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
server {
    if ($host = web-srv1-bao-bab.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name web-srv1-bao-bab.com;
    return 404; # managed by Certbot


}
```

My front are served statically by lws mutualized server

Did you have any idea for fix this problem ?

**Comment by jud3v** [comment]
Maybe someone ?

**Comment by jud3v** [comment]
Fixed by adding *api/*

**Comment by 949mac** [comment]
I'm having the same issue:

![image](https://user-images.githubusercontent.com/23151962/99439664-56d16380-28ca-11eb-964b-dcdc994e8c3e.png)

My GET request works. My POST fails.

Changing `api/*` to `*api/*` did not work for me.

**Comment by jud3v** [comment]
You are in local or production ?

**Comment by 949mac** [comment]
So I just figured it out! It took 2 hours and boy was it a silly one. 

My controller saves a model with a ->save() function. That line through the CORS issue. When I changed it to ->saveQuietly() it resolved the issue. 

I realized that an attached observer was silently failing on me. Doh!

**Comment by jud3v** [comment]
Okay okay, but if the bug come one more time.

Edit your cors

Clear your config and the cache.

Then cache your conf and your apps without changing the conf.

Then wait a little more and clear the cache of you browser or the session, then retry and the cors will be done.
