### ISSUE TITLE
Class Fruitcake\Cors\HandleCors does not exist

### ISSUE THREAD

**Issue by mecjos** [fruitcake/laravel-cors#513]
I get this error. My project is on godaddy shared server. I deleted barryvdh/laravel-cors, earlier cors package, then uploaded fruitcake one. Deleted old service providers and followed the installation guide but get this error.. Any solution for this?

**Comment by sharathm89** [comment]
@mecjos shouldn't it be `\Fruitcake\Cors\HandleCors::class` ?  

this works for me

```
$app->middleware([
    \Fruitcake\Cors\HandleCors::class,
]);
```

**Comment by Mohsin05** [comment]
This issue come with laravel 7

**Comment by tripol** [comment]
In my case, I was able to resolve the issue by clearing my cache, config and optimizing the app.

My app runs on Laravel v8

Commands:
```
php artisan config:cache
php artisan cache:clear
php artisan optimize:clear
```

**Comment by RashedAlmayyas** [comment]
Delete line 18 containing \Fruitcake\Cors\HandleCors::class,

Located in the following path: app/Http/kernel.php
![image](https://user-images.githubusercontent.com/108932239/196030531-60b3154b-a061-4435-aa5e-f940d3d5d1f8.png)

to become
![image](https://user-images.githubusercontent.com/108932239/196030664-06d110c8-8695-436a-8d2e-484b32a3c43b.png)

**Comment by NOORshatnawi** [comment]
good job so beautiful keep going
