### ISSUE TITLE
Laravel-coros block after few hours randomly 

### ISSUE THREAD

**Issue by GEEQ** [fruitcake/laravel-cors#516]
I'm running Laravel environment   with Docker(php-fpm/nginx) the Cors works perfectly when I just start the docker-compose after few hours the cors start blocking the /login endpoint (sanctum) I should do a docker-compose down and docker-compose up -d to get the login authorized again 

![image](https://user-images.githubusercontent.com/9090852/102931348-84e42d80-449e-11eb-87d4-bfd7d615d4ef.png)

![image](https://user-images.githubusercontent.com/9090852/102931387-962d3a00-449e-11eb-90f7-7396ea292372.png)

![image](https://user-images.githubusercontent.com/9090852/102931454-b52bcc00-449e-11eb-95aa-002e2117e97a.png)

Already tried chmod -R 777 storage/ boostrap/cache  and php artisan optimize:clear  / config:clear / cache:clear

it's an issue relative to Laravel-CORS ?

**Comment by GEEQ** [comment]
Notice that i'm using nginx revese proxy

**Comment by barryvdh** [comment]
Are you handling the Vary headers correctly in your reverse proxy?
