### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by Marmahan** [fruitcake/laravel-cors#520]
Hi

Using Laravel 8 and upgrading from laravel cors barryvdh to fruitcake/laravel-cors. Unfortunately, requests are being blocked with the following response:
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource`

The error apears only when i add contentType: "application/json",  to the request

How can I add Access-Control-Allow-Origin?

Edit: Fixed, adding the middleware to the middleware array in http/kernel.php fixed the problem.

**Comment by jackbaron** [comment]
i have a same problem. but it working fine on local, staging environment. on production is not working. do you have a solution?
