### ISSUE TITLE
HandleCors takes 19% of the time to process my requests

### ISSUE THREAD

**Issue by lucianobargmann** [fruitcake/laravel-cors#524]
How can I disable Fruitcake? It is # time consuming element in all my requests:

![image](https://user-images.githubusercontent.com/495852/113462270-8060d680-93f6-11eb-8967-dcc17b611978.png)

**Comment by barryvdh** [comment]
That seems weird, but all of your request logic probably takes place inside the handle, because of the way the middle ware wraps around the rest (onion layers).
But you can just remove the middle ware and package from your app.

**Comment by lucianobargmann** [comment]
Thanks Barry, So you are saying that HandleCors::handle is being reported as the wrapper for all my request in New Relic? I can see my actual request methods being called. I think your package comes with Laravel now. I tried removing it just like you said, and got a bunch of errors - will do more research. THanks for your time.
