### ISSUE TITLE
Memory Leaks in Octane

### ISSUE THREAD

**Issue by themsaid** [fruitcake/laravel-cors#527]
This line creates a memory leak in Octane: https://github.com/fruitcake/laravel-cors/blob/5781ffce1f68cb003a36ddd1c66fcf70bae3c07d/src/HandleCors.php#L51

Event listeners should be registered inside a service provider. Doing this inside a middleware causes the listener to be registered multiple times one on each request.

**Comment by barryvdh** [comment]
Fixed with #469
