### ISSUE TITLE
Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed

### ISSUE THREAD

**Issue by jagoanmamah** [fruitcake/laravel-cors#538]
<img width="1440" alt="Screen Shot 2021-07-06 at 09 18 59" src="https://user-images.githubusercontent.com/25195185/124532849-8625e800-de3b-11eb-8165-687f4df2393d.png">

<img width="550" alt="Screen Shot 2021-07-06 at 10 00 52" src="https://user-images.githubusercontent.com/25195185/124535923-2df1e480-de41-11eb-90df-9953f71a77bb.png">

**Comment by barryvdh** [comment]
Probably you have the headers in your PHP file of .htaccess/nginx already
